/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/ryan/.choosenim/toolchains/nim-0.18.0/lib -o /home/ryan/dev/slackbot/src/nimcache/slackapi_shared.o /home/ryan/dev/slackbot/src/nimcache/slackapi_shared.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w;
typedef struct tyTuple_NNtWKBjakYzBHgg10danlw tyTuple_NNtWKBjakYzBHgg10danlw;
typedef struct tyObject_HttpClientBasecolonObjectType__KIIBrzVNL0pefbQL8QOD6g tyObject_HttpClientBasecolonObjectType__KIIBrzVNL0pefbQL8QOD6g;
typedef struct tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g;
typedef struct tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg;
typedef struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyTuple_jq7X5k7hWG0tdTZTDkiyGQ;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA;
typedef struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w;
typedef struct tyObject_ProxycolonObjectType__CigKkL8U2DnJdbYRi9aI9aoQ tyObject_ProxycolonObjectType__CigKkL8U2DnJdbYRi9aI9aoQ;
typedef struct tyTuple_ddl5jobGD9cEh0GxO7QGFQA tyTuple_ddl5jobGD9cEh0GxO7QGFQA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw;
typedef struct tySequence_4eQHGndY6XBYpFOH09apV8Q tySequence_4eQHGndY6XBYpFOH09apV8Q;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw;
typedef struct tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA;
typedef struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct tyTuple_awOivLjlO76sGdHY7nQUjQ tyTuple_awOivLjlO76sGdHY7nQUjQ;
typedef struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw;
typedef struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
typedef NU8 tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w {
NimStringDesc* token;
tyObject_HttpClientBasecolonObjectType__KIIBrzVNL0pefbQL8QOD6g* client;
tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g* data;
NU16 port;
NimStringDesc* wsUrl;
NU msgId;
tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw* sock;
};
struct tyTuple_NNtWKBjakYzBHgg10danlw {
tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w Field0;
NU Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg {
tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ type_0;
NimStringDesc* channel;
NimStringDesc* text;
};
struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ {
NimStringDesc* Field0;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field1;
};
typedef tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyArray_rhtWm6uYOU6da9bZDT6ryDA[4];
struct tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA {
NimStringDesc* id;
NimStringDesc* name;
};
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
struct tyTuple_ddl5jobGD9cEh0GxO7QGFQA {
tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w Field0;
tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA Field1;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA {
  Exception Sup;
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw {
  Exception Sup;
};
struct tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA {
  Exception Sup;
};
typedef NU8 tyEnum_Opcode_5Q1f2LyzcABs1Zh7wfadZQ;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI64 total, NI64 progress, NI64 speed, void* ClE_0);
void* ClE_0;
} tyProc_mi0JpXKya87ACPD32j5pow;
struct tyObject_HttpClientBasecolonObjectType__KIIBrzVNL0pefbQL8QOD6g {
tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ* socket;
NIM_BOOL connected;
tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ currentURL;
tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers;
NI maxRedirects;
NimStringDesc* userAgent;
NI timeout;
tyObject_ProxycolonObjectType__CigKkL8U2DnJdbYRi9aI9aoQ* proxy;
tyProc_mi0JpXKya87ACPD32j5pow onProgressChanged;
tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext;
NI64 contentTotal;
NI64 contentProgress;
NI64 oneSecondProgress;
NF lastProgressReport;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* bodyStream;
NIM_BOOL getBody;
};
struct tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g {
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* content;
};
typedef NU8 tyEnum_SocketKind_LVqgZYstYjAJSuADJ9bp5XA;
struct tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw {
  RootObj Sup;
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* sock;
NimStringDesc* protocol;
tyEnum_SocketKind_LVqgZYstYjAJSuADJ9bp5XA kind;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
NimStringDesc* stackTrace;
NI id;
NimStringDesc* fromProc;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ {
tySequence_8Np6tlClE5az1CyqZdN19bQ* data;
NI counter;
};
struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w {
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* context;
tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ referencedData;
tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw* extraInternal;
};
struct tyObject_ProxycolonObjectType__CigKkL8U2DnJdbYRi9aI9aoQ {
tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ url;
NimStringDesc* auth;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw* value;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_SocketImpl_aIhANOOoETolVz9cccNO9cRQ {
int fd;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL isSsl;
union{
struct {tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* sslHandle;
tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext;
NIM_BOOL sslNoHandshake;
NIM_BOOL sslHasPeekChar;
NIM_CHAR sslPeekChar;
} S1;
} isSslU;
NI32 lastError;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA {
tyObject_Table_LLQadDAXEvd71UDdEc3lDA* table;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg {
int fd;
NIM_BOOL closed;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL isSsl;
union{
struct {tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* sslHandle;
tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioIn;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioOut;
} S1;
} isSslU;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* identity, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* hint, tyTuple_UV3llMMYFckfui8YMBuUZA* Result, void* ClE_0);
void* ClE_0;
} tyProc_nzIUHFubO43GG203VFo9b7A;
struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw {
  RootObj Sup;
tyProc_lRW9cfxqfm1ql4gkxfLReYg serverGetPskFunc;
tyProc_nzIUHFubO43GG203VFo9b7A clientGetPskFunc;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_4eQHGndY6XBYpFOH09apV8Q {
  TGenericSeq Sup;
  tyTuple_UV3llMMYFckfui8YMBuUZA data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ, stringToSlackRTMType_OYSL8r19a1D7n8Wr11dmQGw)(NimStringDesc* msgType);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, getMessageID_slU1qyja885VXOtE1BOvhQ)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, tyTuple_NNtWKBjakYzBHgg10danlw* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, formatMessageForSend_geR1d3bFlWNeniQ1oU9az8Q)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message, NU msgId);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__9bR9b9aepApwIZEZZtX9cb7RFA)(tyTuple_jq7X5k7hWG0tdTZTDkiyGQ* keyVals, NI keyValsLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__8iXO9aRAijCPe58pujCBbuQ_3)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(void, sendMessage_WZ9bV9bXnMofKShWM5cafUmQ)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result);
N_LIB_PRIVATE N_NIMCALL(void, waitFor_VIKMhEBTNLqEA2ZGnacjrw)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* fut);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, sendText_x0rRA9aTK0lOuGp18EzuY4g)(tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw* ws, NimStringDesc* p, NIM_BOOL masked);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__f9cKpuwjrLNwYtym1kuFzjQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node);
N_LIB_PRIVATE N_NIMCALL(void, newSlackUser_eh9bewG47YRbHv9csgTmimsQ)(tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA* Result);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, parseUserData_9bNKgb241Rw6fIuVZIPdAuQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data, tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr_z2Itmc4KJ7uMBtaTVQ09cqw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NimStringDesc* default_0);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_LIB_PRIVATE N_NIMCALL(void, newSlackMessage_uIr35p52kltkHTESOTuADg)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg* Result);
N_LIB_PRIVATE N_NIMCALL(void, newSlackMessage_CAnJ54I8UckssZ4gbFkv6A)(tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ msgType, NimStringDesc* channel, NimStringDesc* text, tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg* Result);
N_LIB_PRIVATE N_NIMCALL(void, newSlackMessage_RQEuFAUJRxwZq9at2Rxs1wQ)(NimStringDesc* msgType, NimStringDesc* channel, NimStringDesc* text, tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percentstar__VA8Vg9bYt4iyxdojBi10Ebw)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJObject_phgxr9cKlc0dmrJpCth52pw_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, add_n3qm2zfwLtoWXXf3UIj9aeg)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJString_8iXO9aRAijCPe58pujCBbuQ)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__BQFJsdrDy4leoe3FXS7x4w)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message);
N_LIB_PRIVATE N_NIMCALL(void, newRTMConnection_aHSIIce24WpewPa3kYf4vw)(NimStringDesc* token, NI port, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_HttpClientBasecolonObjectType__KIIBrzVNL0pefbQL8QOD6g*, newHttpClient_iNq9cvUMWYFvwNBIZ9aVzxVg)(NimStringDesc* userAgent, NI maxRedirects, tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext, tyObject_ProxycolonObjectType__CigKkL8U2DnJdbYRi9aI9aoQ* proxy, NI timeout);
N_LIB_PRIVATE N_NIMCALL(tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g*, newMultipartData_cWRdpcBQ9cRwNI7BoEq8aVg)(void);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__D8bQiTzlLUrg9b59bmREni9ag)(tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g** p, NimStringDesc* name, NimStringDesc* content);
N_LIB_PRIVATE N_NIMCALL(void, newRTMConnection_9byaPdXJjioG3GimLdTSpvg)(NimStringDesc* token, NU16 port, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result);
N_LIB_PRIVATE N_NIMCALL(void, newRTMConnection_gCXu1dUvM2jHLl0yhTGWIg)(NimStringDesc* token, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isConnected_ACzCBtBZvDGk5dyc7ghaBg)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection);
N_LIB_PRIVATE N_NIMCALL(void, initRTMConnection_fgI38REKioDoQPbZAct9bIQ)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, NIM_BOOL use_start_endpoint, tyTuple_ddl5jobGD9cEh0GxO7QGFQA* Result);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_q2jt59czHU4BW88Mb7EJDUA)(NimStringDesc* buffer);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, postContent_4EDp6iLGHyQqlUjAnT0OEA)(tyObject_HttpClientBasecolonObjectType__KIIBrzVNL0pefbQL8QOD6g* client, NimStringDesc* url, NimStringDesc* body, tyObject_MultipartDatacolonObjectType__pa59bn7R9cBmjUm9clF5koL7g* multipart);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, getCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_VczJ0fz1o49a9ajsD9cvbBPBQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* key);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_5Red8qNVEd2T0lGUaDPoZA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_NIMCALL(void, Marker_tyRef_IrNL59cXPnEUQVBLXMrTE9bA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, initWebsocketConnection_69a68LWBz7zPhoj0pZBd8yA)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuRSplitChar)(NimStringDesc* s, NIM_CHAR sep, NI maxsplit);
N_LIB_PRIVATE N_NIMCALL(void, parseUri_RvyL7IMLrYm3DvIkorH8qQ)(NimStringDesc* uri, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw*, waitFor_nqUmqfjeKI79a3KJk2KCYUA)(tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw* fut);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw*, newAsyncWebsocketClient_LNukzey2nCkzrOcCDrLBBQ)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri, tySequence_4eQHGndY6XBYpFOH09apV8Q* additionalHeaders, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* protocols, NimStringDesc* userAgent, tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* ctx);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w*, defaultSslContext_uAMmYzMx9aT2vpMH6JA9b7Dw)(void);
N_LIB_PRIVATE N_NIMCALL(void, connectToRTM_0cvWcDie8qRvY89a0hv072g)(NimStringDesc* token, NU16 port, tyTuple_ddl5jobGD9cEh0GxO7QGFQA* Result);
N_LIB_PRIVATE N_NIMCALL(void, connectToRTM_WQC7yOzOQXWY9bWllcUzSlQ)(NimStringDesc* token, NI port, tyTuple_ddl5jobGD9cEh0GxO7QGFQA* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getTokenFromConfig_Rb7RDMRaSu882c6f8lhg2w)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosjoinPath)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetConfigDir)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseFile_jHjkbBWx0TRN9bcGqTg49c4A)(NimStringDesc* filename);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_NIMCALL(void, Marker_tyRef_mNHHdog9chWGG2MSH2CNqXQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, writeFile_c1B29b0ZdDRPHc27YaKqwaA)(NimStringDesc* filename, NimStringDesc* content);
static N_NIMCALL(void, Marker_tyRef_4gdZvN5gFqFdHFTecosQ6A)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isTextOpcode_fVtkC9blPL2nqe10PwQ0YxA)(tyEnum_Opcode_5Q1f2LyzcABs1Zh7wfadZQ opcode);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_NNtWKBjakYzBHgg10danlw_;
TNimType NTI_9awtt4aGm78E79cEb4b9bFs4w_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_pHiQBqbN76w0FOsEtyxgEQ_;
extern TNimType NTI_C2BQ9bBtquATvyiqBZFy3Tg_;
extern TNimType NTI_M4na42GvebBMnI5wV9cYMxg_;
extern TNimType NTI_hMQEc0FMry7Up7EoPki79aA_;
extern TNimType NTI_inAXQwjH33JjtLPhTcLm9cg_;
TNimType NTI_H0ILWr9c7hJLj4gA0B4paCQ_;
TNimType NTI_J2AkaUokBr316VD9cYGvAYA_;
TNimType NTI_mFiSKRsUTH7MrCMGm6x4dg_;
extern tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* defaultSSLContext_v4yFHqYk9bUajMnMmP7O9c6A;
TNimType NTI_ddl5jobGD9cEh0GxO7QGFQA_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
TNimType NTI_WYWy8wLatRKYy9c78R4fAbA_;
TNimType NTI_5Red8qNVEd2T0lGUaDPoZA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_RQ9cbM0iZgecIlTaA8WAEPA_;
TNimType NTI_IrNL59cXPnEUQVBLXMrTE9bA_;
extern TNimType NTI_4eQHGndY6XBYpFOH09apV8Q_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
TNimType NTI_8L13g133N2Wr6SiGX9cn8nw_;
TNimType NTI_mNHHdog9chWGG2MSH2CNqXQ_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
TNimType NTI_9c4fposUbks0zxNVErgCzDA_;
TNimType NTI_4gdZvN5gFqFdHFTecosQ6A_;
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_2, "message", 7);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_3, "user_typing", 11);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_4, "group_joined", 12);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_5, "group_open", 10);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_6, "im_created", 10);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_7, "im_open", 7);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_10, "id", 2);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_11, "type", 4);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_15, "channel", 7);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_16, "text", 4);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_18, "not isNil(node) ", 16);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_19, "node.kind == JObject ", 21);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_20, "fields", 6);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_21, "self", 4);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_22, "", 0);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_23, "name", 4);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_25, "Nim httpclient/0.18.0", 21);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_26, "token", 5);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_28, "https://slack.com/api/rtm.", 26);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_29, "start", 5);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_30, "connect", 7);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_32, "url", 3);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_33, "error", 5);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_34, "invalid_auth", 12);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_35, "invalid token", 13);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_36, "failed to connect (reason: $#)", 30);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_37, "$#:443/$#/$#", 12);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_38, "websocket.nim (https://github.com/niv/websocket.nim)", 52);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_39, "failed to connect to websocket", 30);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_40, "nim-slackapi", 12);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_42, "token.cfg", 9);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_44, "No Token key found in config file", 33);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_9bZxUaTPy7yWEccQCxHXsww_43 = {((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_44)}
;
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_45, "no token key found in config", 28);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_46, "No token.cfg file found in $#.\012 Creating a blank one now.\012 Plea"
"se add your token to it", 86);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_47, "{\"token\": \"xxxxx\"}", 18);
STRING_LITERAL(TM_9bZxUaTPy7yWEccQCxHXsww_48, "No token.cfg file found in $#", 29);

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ, stringToSlackRTMType_OYSL8r19a1D7n8Wr11dmQGw)(NimStringDesc* msgType) {
	tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ result;
	nimfr_("stringToSlackRTMType", "shared.nim");
	result = (tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ)0;
	nimln_(79, "shared.nim");
	if (eqStrings(msgType, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_2))) goto LA1_;
	if (eqStrings(msgType, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_3))) goto LA2_;
	if (eqStrings(msgType, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_4))) goto LA3_;
	if (eqStrings(msgType, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_5))) goto LA4_;
	if (eqStrings(msgType, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_6))) goto LA5_;
	if (eqStrings(msgType, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_7))) goto LA6_;
	goto LA7_;
	LA1_: ;
	{
		result = ((tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ) 0);
	}
	goto LA8_;
	LA2_: ;
	{
		result = ((tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ) 1);
	}
	goto LA8_;
	LA3_: ;
	{
		result = ((tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ) 2);
	}
	goto LA8_;
	LA4_: ;
	{
		result = ((tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ) 3);
	}
	goto LA8_;
	LA5_: ;
	{
		result = ((tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ) 4);
	}
	goto LA8_;
	LA6_: ;
	{
		result = ((tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ) 5);
	}
	goto LA8_;
	LA7_: ;
	{
	}
	LA8_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, getMessageID_slU1qyja885VXOtE1BOvhQ)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, tyTuple_NNtWKBjakYzBHgg10danlw* Result) {
	tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w currentConnection;
	NU id;
	nimfr_("getMessageID", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_NNtWKBjakYzBHgg10danlw_));
	memset((void*)(&currentConnection), 0, sizeof(currentConnection));
	nimln_(110, "shared.nim");
	genericAssign((void*)(&currentConnection), (void*)connection, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(111, "shared.nim");
	id = (*connection).msgId;
	nimln_(112, "shared.nim");
	currentConnection.msgId += ((NI) 1);
	nimln_(113, "shared.nim");
	genericAssign((void*)(&(*Result).Field0), (void*)(&currentConnection), (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	(*Result).Field1 = id;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, formatMessageForSend_geR1d3bFlWNeniQ1oU9az8Q)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message, NU msgId) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyArray_rhtWm6uYOU6da9bZDT6ryDA T1_;
	NimStringDesc* T2_;
	nimfr_("formatMessageForSend", "shared.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(121, "shared.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0].Field0 = copyString(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_10));
	nimln_(122, "shared.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__rzAI8EMyNBAQwGODeohhAA(((NU64) (msgId)));
	T1_[0].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(T2_);
	T1_[1].Field0 = copyString(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_11));
	nimln_(123, "shared.nim");
	T1_[1].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(reprEnum((NI)message.type_0, (&NTI_H0ILWr9c7hJLj4gA0B4paCQ_)));
	T1_[2].Field0 = copyString(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_15));
	nimln_(124, "shared.nim");
	T1_[2].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(message.channel);
	T1_[3].Field0 = copyString(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_16));
	nimln_(125, "shared.nim");
	T1_[3].Field1 = percent__8iXO9aRAijCPe58pujCBbuQ_3(message.text);
	result = percent__9bR9b9aepApwIZEZZtX9cb7RFA(T1_, 4);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, sendMessage_WZ9bV9bXnMofKShWM5cafUmQ)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result) {
	tyTuple_NNtWKBjakYzBHgg10danlw T1_;
	tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w conn;
	NU id;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* formattedMessage;
	NimStringDesc* T2_;
	tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* T3_;
	nimfr_("sendMessage", "shared.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(133, "shared.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	getMessageID_slU1qyja885VXOtE1BOvhQ(connection, (&T1_));
	memset((void*)(&conn), 0, sizeof(conn));
	memcpy((void*)(&conn), (NIM_CONST void*)(&T1_.Field0), sizeof(conn));
	id = (NU)0;
	id = T1_.Field1;
	nimln_(134, "shared.nim");
	formattedMessage = formatMessageForSend_geR1d3bFlWNeniQ1oU9az8Q(message, id);
	nimln_(135, "shared.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__f9cKpuwjrLNwYtym1kuFzjQ(formattedMessage);
	T3_ = (tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*)0;
	T3_ = sendText_x0rRA9aTK0lOuGp18EzuY4g(conn.sock, T2_, NIM_TRUE);
	waitFor_VIKMhEBTNLqEA2ZGnacjrw(T3_);
	nimln_(136, "shared.nim");
	genericAssign((void*)Result, (void*)(&conn), (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newSlackUser_eh9bewG47YRbHv9csgTmimsQ)(tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA* Result) {
	nimfr_("newSlackUser", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_J2AkaUokBr316VD9cYGvAYA_));
	nimln_(142, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).id), rawNewString(((NI) 255)));
	nimln_(143, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).name), rawNewString(((NI) 255)));
	popFrame();
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, X5BX5D__bm6Lzuv1zmaV42IeMuikggjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node, NimStringDesc* name) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q** T9_;
	nimfr_("[]", "json.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(920, "json.nim");
	{
		if (!!(!((node == 0)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_18));
	}
	LA3_: ;
	nimln_(921, "json.nim");
	{
		if (!!(((*node).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA7_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_19));
	}
	LA7_: ;
	nimln_(924, "json.nim");
	if (!(((32 &(1U<<((NU)((*node).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_20));
	T9_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q**)0;
	T9_ = X5BX5D__9bcSZUFhwESDEYXhkxOm8Hg((&(*node).kindU.S6.fields), name);
	result = (*T9_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseUserData_9bNKgb241Rw6fIuVZIPdAuQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data, tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA* Result) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T2_;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T3_;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T4_;
	nimfr_("parseUserData", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_J2AkaUokBr316VD9cYGvAYA_));
	nimln_(149, "shared.nim");
	newSlackUser_eh9bewG47YRbHv9csgTmimsQ(Result);
	nimln_(150, "shared.nim");
	T1_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T1_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(data, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_21));
	T2_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T2_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(T1_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_10));
	unsureAsgnRef((void**) (&(*Result).id), getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T2_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22)));
	nimln_(151, "shared.nim");
	T3_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T3_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(data, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_21));
	T4_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T4_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(T3_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_23));
	unsureAsgnRef((void**) (&(*Result).name), getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T4_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newSlackMessage_uIr35p52kltkHTESOTuADg)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg* Result) {
	nimfr_("newSlackMessage", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_mFiSKRsUTH7MrCMGm6x4dg_));
	nimln_(154, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).channel), rawNewString(((NI) 255)));
	nimln_(155, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).text), rawNewString(((NI) 8192)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newSlackMessage_CAnJ54I8UckssZ4gbFkv6A)(tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ msgType, NimStringDesc* channel, NimStringDesc* text, tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg* Result) {
	nimfr_("newSlackMessage", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_mFiSKRsUTH7MrCMGm6x4dg_));
	nimln_(165, "shared.nim");
	newSlackMessage_uIr35p52kltkHTESOTuADg(Result);
	nimln_(166, "shared.nim");
	(*Result).type_0 = msgType;
	nimln_(167, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).channel), copyString(channel));
	nimln_(168, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).text), copyString(text));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newSlackMessage_RQEuFAUJRxwZq9at2Rxs1wQ)(NimStringDesc* msgType, NimStringDesc* channel, NimStringDesc* text, tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg* Result) {
	tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ messageType;
	nimfr_("newSlackMessage", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_mFiSKRsUTH7MrCMGm6x4dg_));
	nimln_(171, "shared.nim");
	messageType = stringToSlackRTMType_OYSL8r19a1D7n8Wr11dmQGw(msgType);
	nimln_(172, "shared.nim");
	newSlackMessage_CAnJ54I8UckssZ4gbFkv6A(messageType, channel, text, Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percentstar__VA8Vg9bYt4iyxdojBi10Ebw)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T2_;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T3_;
	nimfr_("%*", "shared.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(178, "shared.nim");
	result = newJObject_phgxr9cKlc0dmrJpCth52pw_2();
	nimln_(179, "shared.nim");
	T1_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T1_ = newJString_8iXO9aRAijCPe58pujCBbuQ(reprEnum((NI)message.type_0, (&NTI_H0ILWr9c7hJLj4gA0B4paCQ_)));
	add_n3qm2zfwLtoWXXf3UIj9aeg(result, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_11), T1_);
	nimln_(180, "shared.nim");
	T2_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T2_ = newJString_8iXO9aRAijCPe58pujCBbuQ(message.channel);
	add_n3qm2zfwLtoWXXf3UIj9aeg(result, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_15), T2_);
	nimln_(181, "shared.nim");
	T3_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T3_ = newJString_8iXO9aRAijCPe58pujCBbuQ(message.text);
	add_n3qm2zfwLtoWXXf3UIj9aeg(result, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_2), T3_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__BQFJsdrDy4leoe3FXS7x4w)(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg message) {
	NimStringDesc* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	nimfr_("$", "shared.nim");
	result = (NimStringDesc*)0;
	nimln_(184, "shared.nim");
	T1_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T1_ = percentstar__VA8Vg9bYt4iyxdojBi10Ebw(message);
	result = dollar__f9cKpuwjrLNwYtym1kuFzjQ(T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, newRTMConnection_aHSIIce24WpewPa3kYf4vw)(NimStringDesc* token, NI port, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result) {
	nimfr_("newRTMConnection", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(190, "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	unsureAsgnRef((void**) (&(*Result).token), copyString(token));
	nimln_(220, "httpclient.nim");
	unsureAsgnRef((void**) (&(*Result).client), newHttpClient_iNq9cvUMWYFvwNBIZ9aVzxVg(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_25), ((NI) 5), defaultSSLContext_v4yFHqYk9bUajMnMmP7O9c6A, NIM_NIL, ((NI) -1)));
	nimln_(190, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).data), newMultipartData_cWRdpcBQ9cRwNI7BoEq8aVg());
	(*Result).port = ((NU16) (port));
	(*Result).msgId = ((NU) 1);
	unsureAsgnRef((void**) (&(*Result).sock), NIM_NIL);
	nimln_(191, "shared.nim");
	X5BX5Deq__D8bQiTzlLUrg9b59bmREni9ag(&(*Result).data, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_26), token);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newRTMConnection_9byaPdXJjioG3GimLdTSpvg)(NimStringDesc* token, NU16 port, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result) {
	nimfr_("newRTMConnection", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(197, "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	unsureAsgnRef((void**) (&(*Result).token), copyString(token));
	nimln_(220, "httpclient.nim");
	unsureAsgnRef((void**) (&(*Result).client), newHttpClient_iNq9cvUMWYFvwNBIZ9aVzxVg(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_25), ((NI) 5), defaultSSLContext_v4yFHqYk9bUajMnMmP7O9c6A, NIM_NIL, ((NI) -1)));
	nimln_(197, "shared.nim");
	unsureAsgnRef((void**) (&(*Result).data), newMultipartData_cWRdpcBQ9cRwNI7BoEq8aVg());
	(*Result).port = port;
	(*Result).msgId = ((NU) 1);
	unsureAsgnRef((void**) (&(*Result).sock), NIM_NIL);
	nimln_(198, "shared.nim");
	X5BX5Deq__D8bQiTzlLUrg9b59bmREni9ag(&(*Result).data, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_26), token);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newRTMConnection_gCXu1dUvM2jHLl0yhTGWIg)(NimStringDesc* token, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result) {
	nimfr_("newRTMConnection", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(204, "shared.nim");
	newRTMConnection_9byaPdXJjioG3GimLdTSpvg(token, ((NU16) 443), Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isConnected_ACzCBtBZvDGk5dyc7ghaBg)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection) {
	NIM_BOOL result;
	nimfr_("isConnected", "shared.nim");
	result = (NIM_BOOL)0;
	nimln_(210, "shared.nim");
	result = !(((*connection).sock == 0));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_5Red8qNVEd2T0lGUaDPoZA)(void* p, NI op) {
	tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA* a;
	a = (tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_IrNL59cXPnEUQVBLXMrTE9bA)(void* p, NI op) {
	tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA* a;
	a = (tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_LIB_PRIVATE N_NIMCALL(void, initRTMConnection_fgI38REKioDoQPbZAct9bIQ)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, NIM_BOOL use_start_endpoint, tyTuple_ddl5jobGD9cEh0GxO7QGFQA* Result) {
	NimStringDesc* url;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* jsResponse;
	NimStringDesc* T8_;
	TSafePoint TM_9bZxUaTPy7yWEccQCxHXsww_31;
	nimfr_("initRTMConnection", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_ddl5jobGD9cEh0GxO7QGFQA_));
	nimln_(218, "shared.nim");
	genericAssign((void*)(&(*Result).Field0), (void*)connection, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(219, "shared.nim");
	url = copyString(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_28));
	nimln_(220, "shared.nim");
	{
		NimStringDesc* T5_;
		if (!use_start_endpoint) goto LA3_;
		nimln_(221, "shared.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = rawNewString(url->Sup.len + 5);
appendString(T5_, url);
appendString(T5_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_29));
		url = T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T7_;
		nimln_(223, "shared.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = rawNewString(url->Sup.len + 7);
appendString(T7_, url);
appendString(T7_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_30));
		url = T7_;
	}
	LA1_: ;
	nimln_(225, "shared.nim");
	T8_ = (NimStringDesc*)0;
	T8_ = postContent_4EDp6iLGHyQqlUjAnT0OEA((*connection).client, url, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22), (*connection).data);
	jsResponse = parseJson_q2jt59czHU4BW88Mb7EJDUA(T8_);
	nimln_(226, "shared.nim");
	pushSafePoint(&TM_9bZxUaTPy7yWEccQCxHXsww_31);
	TM_9bZxUaTPy7yWEccQCxHXsww_31.status = setjmp(TM_9bZxUaTPy7yWEccQCxHXsww_31.context);
	if (TM_9bZxUaTPy7yWEccQCxHXsww_31.status == 0) {
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T10_;
		nimln_(227, "shared.nim");
		T10_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		T10_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsResponse, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_32));
		unsureAsgnRef((void**) (&(*Result).Field0.wsUrl), getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T10_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22)));
		nimln_(228, "shared.nim");
		parseUserData_9bNKgb241Rw6fIuVZIPdAuQ(jsResponse, (&(*Result).Field1));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_))) {
			TM_9bZxUaTPy7yWEccQCxHXsww_31.status = 0;
			nimln_(230, "shared.nim");
			{
				NIM_BOOL T15_;
				T15_ = (NIM_BOOL)0;
				T15_ = hasKey_VczJ0fz1o49a9ajsD9cvbBPBQ(jsResponse, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_33));
				if (!T15_) goto LA16_;
				nimln_(231, "shared.nim");
				{
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T20_;
					NimStringDesc* T21_;
					tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA* e;
					NimStringDesc* T24_;
					T20_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
					T20_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsResponse, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_33));
					T21_ = (NimStringDesc*)0;
					T21_ = getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T20_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22));
					if (!eqStrings(T21_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_34))) goto LA22_;
					e = (tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA*)0;
					nimln_(2811, "system.nim");
					e = (tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA*) newObj((&NTI_5Red8qNVEd2T0lGUaDPoZA_), sizeof(tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA));
					(*e).Sup.Sup.m_type = (&NTI_WYWy8wLatRKYy9c78R4fAbA_);
					nimln_(232, "shared.nim");
					T24_ = (NimStringDesc*)0;
					T24_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_35));
					if (T24_) nimGCunrefNoCycle(T24_);
					nimln_(2806, "system.nim");
					asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
					nimln_(232, "shared.nim");
					raiseException((Exception*)e, "InvalidAuthException");
				}
				goto LA18_;
				LA22_: ;
				{
					tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA* e_2;
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T26_;
					NimStringDesc* T27_;
					e_2 = (tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA*)0;
					nimln_(2811, "system.nim");
					e_2 = (tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA*) newObj((&NTI_IrNL59cXPnEUQVBLXMrTE9bA_), sizeof(tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA));
					(*e_2).Sup.Sup.m_type = (&NTI_RQ9cbM0iZgecIlTaA8WAEPA_);
					nimln_(234, "shared.nim");
					T26_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
					T26_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(jsResponse, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_33));
					T27_ = (NimStringDesc*)0;
					T27_ = getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T26_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22));
					asgnRefNoCycle((void**) (&(*e_2).Sup.message), nsuFormatSingleElem(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_36), T27_));
					nimln_(2806, "system.nim");
					asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
					nimln_(234, "shared.nim");
					raiseException((Exception*)e_2, "FailedToConnectException");
				}
				LA18_: ;
			}
			LA16_: ;
			popCurrentException();
		}
	}
	if (TM_9bZxUaTPy7yWEccQCxHXsww_31.status != 0) reraiseException();
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initWebsocketConnection_69a68LWBz7zPhoj0pZBd8yA)(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* connection, tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w* Result) {
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* components;
	tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ uri;
	NimStringDesc* T1_;
	tySequence_4eQHGndY6XBYpFOH09apV8Q* T2_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T3_;
	tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* T4_;
	tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw* T5_;
	nimfr_("initWebsocketConnection", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(240, "shared.nim");
	genericAssign((void*)Result, (void*)connection, (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	nimln_(241, "shared.nim");
	components = nsuRSplitChar((*connection).wsUrl, 47, ((NI) 2));
	memset((void*)(&uri), 0, sizeof(uri));
	nimln_(242, "shared.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = nsuFormatOpenArray(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_37), components->data, components->Sup.len);
	parseUri_RvyL7IMLrYm3DvIkorH8qQ(T1_, (&uri));
	nimln_(244, "shared.nim");
	T2_ = (tySequence_4eQHGndY6XBYpFOH09apV8Q*)0;
	T2_ = (tySequence_4eQHGndY6XBYpFOH09apV8Q*) newSeq((&NTI_4eQHGndY6XBYpFOH09apV8Q_), 0);
	T3_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T3_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(127, "client.nim");
	T4_ = (tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w*)0;
	T4_ = defaultSslContext_uAMmYzMx9aT2vpMH6JA9b7Dw();
	T5_ = (tyObject_FuturecolonObjectType__MTJWwYxyRLohPwUaKD9cNJw*)0;
	T5_ = newAsyncWebsocketClient_LNukzey2nCkzrOcCDrLBBQ((&uri), T2_, T3_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_38), T4_);
	unsureAsgnRef((void**) (&(*Result).sock), waitFor_nqUmqfjeKI79a3KJk2KCYUA(T5_));
	nimln_(245, "shared.nim");
	{
		NIM_BOOL T8_;
		tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA* e;
		NimStringDesc* T11_;
		T8_ = (NIM_BOOL)0;
		T8_ = isConnected_ACzCBtBZvDGk5dyc7ghaBg(Result);
		if (!!(T8_)) goto LA9_;
		e = (tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA*) newObj((&NTI_IrNL59cXPnEUQVBLXMrTE9bA_), sizeof(tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA));
		(*e).Sup.Sup.m_type = (&NTI_RQ9cbM0iZgecIlTaA8WAEPA_);
		nimln_(246, "shared.nim");
		T11_ = (NimStringDesc*)0;
		T11_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_39));
		if (T11_) nimGCunrefNoCycle(T11_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(246, "shared.nim");
		raiseException((Exception*)e, "FailedToConnectException");
	}
	LA9_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, connectToRTM_0cvWcDie8qRvY89a0hv072g)(NimStringDesc* token, NU16 port, tyTuple_ddl5jobGD9cEh0GxO7QGFQA* Result) {
	tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w connection;
	tyTuple_ddl5jobGD9cEh0GxO7QGFQA T1_;
	tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w validatedConnection;
	tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA user;
	nimfr_("connectToRTM", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_ddl5jobGD9cEh0GxO7QGFQA_));
	memset((void*)(&connection), 0, sizeof(connection));
	nimln_(253, "shared.nim");
	newRTMConnection_9byaPdXJjioG3GimLdTSpvg(token, port, (&connection));
	nimln_(255, "shared.nim");
	memset((void*)(&T1_), 0, sizeof(T1_));
	initRTMConnection_fgI38REKioDoQPbZAct9bIQ((&connection), NIM_FALSE, (&T1_));
	memset((void*)(&validatedConnection), 0, sizeof(validatedConnection));
	memcpy((void*)(&validatedConnection), (NIM_CONST void*)(&T1_.Field0), sizeof(validatedConnection));
	memset((void*)(&user), 0, sizeof(user));
	user.id = T1_.Field1.id;
	user.name = T1_.Field1.name;
	nimln_(257, "shared.nim");
	initWebsocketConnection_69a68LWBz7zPhoj0pZBd8yA((&validatedConnection), (&connection));
	nimln_(258, "shared.nim");
	genericAssign((void*)(&(*Result).Field0), (void*)(&connection), (&NTI_9awtt4aGm78E79cEb4b9bFs4w_));
	unsureAsgnRef((void**) (&(*Result).Field1.id), copyString(user.id));
	unsureAsgnRef((void**) (&(*Result).Field1.name), copyString(user.name));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, connectToRTM_WQC7yOzOQXWY9bWllcUzSlQ)(NimStringDesc* token, NI port, tyTuple_ddl5jobGD9cEh0GxO7QGFQA* Result) {
	nimfr_("connectToRTM", "shared.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_ddl5jobGD9cEh0GxO7QGFQA_));
	nimln_(265, "shared.nim");
	connectToRTM_0cvWcDie8qRvY89a0hv072g(token, ((NU16) (port)), Result);
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_mNHHdog9chWGG2MSH2CNqXQ)(void* p, NI op) {
	tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw* a;
	a = (tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}
static N_NIMCALL(void, Marker_tyRef_4gdZvN5gFqFdHFTecosQ6A)(void* p, NI op) {
	tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA* a;
	a = (tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.up, op);
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getTokenFromConfig_Rb7RDMRaSu882c6f8lhg2w)(void) {
	NimStringDesc* volatile result;
	NimStringDesc* config;
	NimStringDesc* T1_;
	TSafePoint TM_9bZxUaTPy7yWEccQCxHXsww_41;
	nimfr_("getTokenFromConfig", "shared.nim");
	result = (NimStringDesc*)0;
	nimln_(272, "shared.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = nosgetConfigDir();
	config = nosjoinPath(T1_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_40));
	nimln_(274, "shared.nim");
	pushSafePoint(&TM_9bZxUaTPy7yWEccQCxHXsww_41);
	TM_9bZxUaTPy7yWEccQCxHXsww_41.status = setjmp(TM_9bZxUaTPy7yWEccQCxHXsww_41.context);
	if (TM_9bZxUaTPy7yWEccQCxHXsww_41.status == 0) {
		NimStringDesc* T3_;
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T4_;
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T5_;
		nimln_(275, "shared.nim");
		T3_ = (NimStringDesc*)0;
		T3_ = nosjoinPath(config, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_42));
		T4_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		T4_ = parseFile_jHjkbBWx0TRN9bcGqTg49c4A(T3_);
		T5_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		T5_ = X5BX5D__bm6Lzuv1zmaV42IeMuikggjson(T4_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_26));
		result = getStr_z2Itmc4KJ7uMBtaTVQ09cqw(T5_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_22));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
		if (isObj(getCurrentException()->Sup.m_type, (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_))) {
			tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw* e;
			NimStringDesc* T8_;
			TM_9bZxUaTPy7yWEccQCxHXsww_41.status = 0;
			nimln_(277, "shared.nim");
			echoBinSafe(TM_9bZxUaTPy7yWEccQCxHXsww_43, 1);
			e = (tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw*)0;
			nimln_(2811, "system.nim");
			e = (tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw*) newObj((&NTI_mNHHdog9chWGG2MSH2CNqXQ_), sizeof(tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw));
			(*e).Sup.Sup.m_type = (&NTI_8L13g133N2Wr6SiGX9cn8nw_);
			nimln_(278, "shared.nim");
			T8_ = (NimStringDesc*)0;
			T8_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_45));
			if (T8_) nimGCunrefNoCycle(T8_);
			nimln_(2806, "system.nim");
			asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
			nimln_(278, "shared.nim");
			raiseException((Exception*)e, "InvalidConfigurationException");
			popCurrentException();
		}
		else 		if (isObj(getCurrentException()->Sup.m_type, (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_))) {
			tyArray_nHXaesL0DJZHyVS07ARPRA T10_;
			NimStringDesc* T11_;
			tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA* e_2;
			TM_9bZxUaTPy7yWEccQCxHXsww_41.status = 0;
			nimln_(280, "shared.nim");
			memset((void*)T10_, 0, sizeof(T10_));
			T10_[0] = nsuFormatSingleElem(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_46), config);
			echoBinSafe(T10_, 1);
			nimln_(281, "shared.nim");
			T11_ = (NimStringDesc*)0;
			T11_ = nosjoinPath(config, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_42));
			writeFile_c1B29b0ZdDRPHc27YaKqwaA(T11_, ((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_47));
			e_2 = (tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA*)0;
			nimln_(2811, "system.nim");
			e_2 = (tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA*) newObj((&NTI_4gdZvN5gFqFdHFTecosQ6A_), sizeof(tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA));
			(*e_2).Sup.Sup.m_type = (&NTI_9c4fposUbks0zxNVErgCzDA_);
			nimln_(282, "shared.nim");
			asgnRefNoCycle((void**) (&(*e_2).Sup.message), nsuFormatSingleElem(((NimStringDesc*) &TM_9bZxUaTPy7yWEccQCxHXsww_48), config));
			nimln_(2806, "system.nim");
			asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
			nimln_(282, "shared.nim");
			raiseException((Exception*)e_2, "MissingConfigFile");
			popCurrentException();
		}
	}
	if (TM_9bZxUaTPy7yWEccQCxHXsww_41.status != 0) reraiseException();
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isTextOpcode_fVtkC9blPL2nqe10PwQ0YxA)(tyEnum_Opcode_5Q1f2LyzcABs1Zh7wfadZQ opcode) {
	NIM_BOOL result;
	nimfr_("isTextOpcode", "shared.nim");
	result = (NIM_BOOL)0;
	nimln_(285, "shared.nim");
	result = (opcode == ((tyEnum_Opcode_5Q1f2LyzcABs1Zh7wfadZQ) 1));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, slackapi_sharedInit000)(void) {
	nimfr_("shared", "shared.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, slackapi_sharedDatInit000)(void) {
static TNimNode* TM_9bZxUaTPy7yWEccQCxHXsww_8[2];
static TNimNode* TM_9bZxUaTPy7yWEccQCxHXsww_9[7];
static TNimNode* TM_9bZxUaTPy7yWEccQCxHXsww_12[6];
NI TM_9bZxUaTPy7yWEccQCxHXsww_14;
static char* NIM_CONST TM_9bZxUaTPy7yWEccQCxHXsww_13[6] = {
"message", 
"user_typing", 
"group_joined", 
"group_open", 
"im_created", 
"im_open"};
static TNimNode* TM_9bZxUaTPy7yWEccQCxHXsww_17[2];
static TNimNode* TM_9bZxUaTPy7yWEccQCxHXsww_24[3];
static TNimNode* TM_9bZxUaTPy7yWEccQCxHXsww_27[2];
static TNimNode TM_9bZxUaTPy7yWEccQCxHXsww_0[32];
NTI_NNtWKBjakYzBHgg10danlw_.size = sizeof(tyTuple_NNtWKBjakYzBHgg10danlw);
NTI_NNtWKBjakYzBHgg10danlw_.kind = 18;
NTI_NNtWKBjakYzBHgg10danlw_.base = 0;
TM_9bZxUaTPy7yWEccQCxHXsww_8[0] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[1];
NTI_9awtt4aGm78E79cEb4b9bFs4w_.size = sizeof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w);
NTI_9awtt4aGm78E79cEb4b9bFs4w_.kind = 18;
NTI_9awtt4aGm78E79cEb4b9bFs4w_.base = 0;
TM_9bZxUaTPy7yWEccQCxHXsww_9[0] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[3];
TM_9bZxUaTPy7yWEccQCxHXsww_0[3].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[3].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, token);
TM_9bZxUaTPy7yWEccQCxHXsww_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[3].name = "token";
TM_9bZxUaTPy7yWEccQCxHXsww_9[1] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[4];
TM_9bZxUaTPy7yWEccQCxHXsww_0[4].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[4].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, client);
TM_9bZxUaTPy7yWEccQCxHXsww_0[4].typ = (&NTI_pHiQBqbN76w0FOsEtyxgEQ_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[4].name = "client";
TM_9bZxUaTPy7yWEccQCxHXsww_9[2] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[5];
TM_9bZxUaTPy7yWEccQCxHXsww_0[5].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[5].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, data);
TM_9bZxUaTPy7yWEccQCxHXsww_0[5].typ = (&NTI_C2BQ9bBtquATvyiqBZFy3Tg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[5].name = "data";
TM_9bZxUaTPy7yWEccQCxHXsww_9[3] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[6];
TM_9bZxUaTPy7yWEccQCxHXsww_0[6].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[6].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, port);
TM_9bZxUaTPy7yWEccQCxHXsww_0[6].typ = (&NTI_M4na42GvebBMnI5wV9cYMxg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[6].name = "port";
TM_9bZxUaTPy7yWEccQCxHXsww_9[4] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[7];
TM_9bZxUaTPy7yWEccQCxHXsww_0[7].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[7].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, wsUrl);
TM_9bZxUaTPy7yWEccQCxHXsww_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[7].name = "wsUrl";
TM_9bZxUaTPy7yWEccQCxHXsww_9[5] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[8];
TM_9bZxUaTPy7yWEccQCxHXsww_0[8].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[8].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, msgId);
TM_9bZxUaTPy7yWEccQCxHXsww_0[8].typ = (&NTI_hMQEc0FMry7Up7EoPki79aA_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[8].name = "msgId";
TM_9bZxUaTPy7yWEccQCxHXsww_9[6] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[9];
TM_9bZxUaTPy7yWEccQCxHXsww_0[9].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[9].offset = offsetof(tyObject_RTMConnection_9awtt4aGm78E79cEb4b9bFs4w, sock);
TM_9bZxUaTPy7yWEccQCxHXsww_0[9].typ = (&NTI_inAXQwjH33JjtLPhTcLm9cg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[9].name = "sock";
TM_9bZxUaTPy7yWEccQCxHXsww_0[2].len = 7; TM_9bZxUaTPy7yWEccQCxHXsww_0[2].kind = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[2].sons = &TM_9bZxUaTPy7yWEccQCxHXsww_9[0];
NTI_9awtt4aGm78E79cEb4b9bFs4w_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[2];
TM_9bZxUaTPy7yWEccQCxHXsww_0[1].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[1].offset = offsetof(tyTuple_NNtWKBjakYzBHgg10danlw, Field0);
TM_9bZxUaTPy7yWEccQCxHXsww_0[1].typ = (&NTI_9awtt4aGm78E79cEb4b9bFs4w_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[1].name = "Field0";
TM_9bZxUaTPy7yWEccQCxHXsww_8[1] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[10];
TM_9bZxUaTPy7yWEccQCxHXsww_0[10].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[10].offset = offsetof(tyTuple_NNtWKBjakYzBHgg10danlw, Field1);
TM_9bZxUaTPy7yWEccQCxHXsww_0[10].typ = (&NTI_hMQEc0FMry7Up7EoPki79aA_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[10].name = "Field1";
TM_9bZxUaTPy7yWEccQCxHXsww_0[0].len = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[0].kind = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[0].sons = &TM_9bZxUaTPy7yWEccQCxHXsww_8[0];
NTI_NNtWKBjakYzBHgg10danlw_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[0];
NTI_H0ILWr9c7hJLj4gA0B4paCQ_.size = sizeof(tyEnum_SlackRTMType_H0ILWr9c7hJLj4gA0B4paCQ);
NTI_H0ILWr9c7hJLj4gA0B4paCQ_.kind = 14;
NTI_H0ILWr9c7hJLj4gA0B4paCQ_.base = 0;
NTI_H0ILWr9c7hJLj4gA0B4paCQ_.flags = 3;
for (TM_9bZxUaTPy7yWEccQCxHXsww_14 = 0; TM_9bZxUaTPy7yWEccQCxHXsww_14 < 6; TM_9bZxUaTPy7yWEccQCxHXsww_14++) {
TM_9bZxUaTPy7yWEccQCxHXsww_0[TM_9bZxUaTPy7yWEccQCxHXsww_14+11].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[TM_9bZxUaTPy7yWEccQCxHXsww_14+11].offset = TM_9bZxUaTPy7yWEccQCxHXsww_14;
TM_9bZxUaTPy7yWEccQCxHXsww_0[TM_9bZxUaTPy7yWEccQCxHXsww_14+11].name = TM_9bZxUaTPy7yWEccQCxHXsww_13[TM_9bZxUaTPy7yWEccQCxHXsww_14];
TM_9bZxUaTPy7yWEccQCxHXsww_12[TM_9bZxUaTPy7yWEccQCxHXsww_14] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[TM_9bZxUaTPy7yWEccQCxHXsww_14+11];
}
TM_9bZxUaTPy7yWEccQCxHXsww_0[17].len = 6; TM_9bZxUaTPy7yWEccQCxHXsww_0[17].kind = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[17].sons = &TM_9bZxUaTPy7yWEccQCxHXsww_12[0];
NTI_H0ILWr9c7hJLj4gA0B4paCQ_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[17];
NTI_J2AkaUokBr316VD9cYGvAYA_.size = sizeof(tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA);
NTI_J2AkaUokBr316VD9cYGvAYA_.kind = 18;
NTI_J2AkaUokBr316VD9cYGvAYA_.base = 0;
NTI_J2AkaUokBr316VD9cYGvAYA_.flags = 2;
TM_9bZxUaTPy7yWEccQCxHXsww_17[0] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[19];
TM_9bZxUaTPy7yWEccQCxHXsww_0[19].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[19].offset = offsetof(tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA, id);
TM_9bZxUaTPy7yWEccQCxHXsww_0[19].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[19].name = "id";
TM_9bZxUaTPy7yWEccQCxHXsww_17[1] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[20];
TM_9bZxUaTPy7yWEccQCxHXsww_0[20].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[20].offset = offsetof(tyObject_SlackUser_J2AkaUokBr316VD9cYGvAYA, name);
TM_9bZxUaTPy7yWEccQCxHXsww_0[20].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[20].name = "name";
TM_9bZxUaTPy7yWEccQCxHXsww_0[18].len = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[18].kind = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[18].sons = &TM_9bZxUaTPy7yWEccQCxHXsww_17[0];
NTI_J2AkaUokBr316VD9cYGvAYA_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[18];
NTI_mFiSKRsUTH7MrCMGm6x4dg_.size = sizeof(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg);
NTI_mFiSKRsUTH7MrCMGm6x4dg_.kind = 18;
NTI_mFiSKRsUTH7MrCMGm6x4dg_.base = 0;
NTI_mFiSKRsUTH7MrCMGm6x4dg_.flags = 2;
TM_9bZxUaTPy7yWEccQCxHXsww_24[0] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[22];
TM_9bZxUaTPy7yWEccQCxHXsww_0[22].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[22].offset = offsetof(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg, type_0);
TM_9bZxUaTPy7yWEccQCxHXsww_0[22].typ = (&NTI_H0ILWr9c7hJLj4gA0B4paCQ_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[22].name = "type";
TM_9bZxUaTPy7yWEccQCxHXsww_24[1] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[23];
TM_9bZxUaTPy7yWEccQCxHXsww_0[23].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[23].offset = offsetof(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg, channel);
TM_9bZxUaTPy7yWEccQCxHXsww_0[23].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[23].name = "channel";
TM_9bZxUaTPy7yWEccQCxHXsww_24[2] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[24];
TM_9bZxUaTPy7yWEccQCxHXsww_0[24].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[24].offset = offsetof(tyObject_SlackMessage_mFiSKRsUTH7MrCMGm6x4dg, text);
TM_9bZxUaTPy7yWEccQCxHXsww_0[24].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[24].name = "text";
TM_9bZxUaTPy7yWEccQCxHXsww_0[21].len = 3; TM_9bZxUaTPy7yWEccQCxHXsww_0[21].kind = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[21].sons = &TM_9bZxUaTPy7yWEccQCxHXsww_24[0];
NTI_mFiSKRsUTH7MrCMGm6x4dg_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[21];
NTI_ddl5jobGD9cEh0GxO7QGFQA_.size = sizeof(tyTuple_ddl5jobGD9cEh0GxO7QGFQA);
NTI_ddl5jobGD9cEh0GxO7QGFQA_.kind = 18;
NTI_ddl5jobGD9cEh0GxO7QGFQA_.base = 0;
TM_9bZxUaTPy7yWEccQCxHXsww_27[0] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[26];
TM_9bZxUaTPy7yWEccQCxHXsww_0[26].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[26].offset = offsetof(tyTuple_ddl5jobGD9cEh0GxO7QGFQA, Field0);
TM_9bZxUaTPy7yWEccQCxHXsww_0[26].typ = (&NTI_9awtt4aGm78E79cEb4b9bFs4w_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[26].name = "Field0";
TM_9bZxUaTPy7yWEccQCxHXsww_27[1] = &TM_9bZxUaTPy7yWEccQCxHXsww_0[27];
TM_9bZxUaTPy7yWEccQCxHXsww_0[27].kind = 1;
TM_9bZxUaTPy7yWEccQCxHXsww_0[27].offset = offsetof(tyTuple_ddl5jobGD9cEh0GxO7QGFQA, Field1);
TM_9bZxUaTPy7yWEccQCxHXsww_0[27].typ = (&NTI_J2AkaUokBr316VD9cYGvAYA_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[27].name = "Field1";
TM_9bZxUaTPy7yWEccQCxHXsww_0[25].len = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[25].kind = 2; TM_9bZxUaTPy7yWEccQCxHXsww_0[25].sons = &TM_9bZxUaTPy7yWEccQCxHXsww_27[0];
NTI_ddl5jobGD9cEh0GxO7QGFQA_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[25];
NTI_WYWy8wLatRKYy9c78R4fAbA_.size = sizeof(tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA);
NTI_WYWy8wLatRKYy9c78R4fAbA_.kind = 17;
NTI_WYWy8wLatRKYy9c78R4fAbA_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[28].len = 0; TM_9bZxUaTPy7yWEccQCxHXsww_0[28].kind = 2;
NTI_WYWy8wLatRKYy9c78R4fAbA_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[28];
NTI_5Red8qNVEd2T0lGUaDPoZA_.size = sizeof(tyObject_InvalidAuthException_WYWy8wLatRKYy9c78R4fAbA*);
NTI_5Red8qNVEd2T0lGUaDPoZA_.kind = 22;
NTI_5Red8qNVEd2T0lGUaDPoZA_.base = (&NTI_WYWy8wLatRKYy9c78R4fAbA_);
NTI_5Red8qNVEd2T0lGUaDPoZA_.marker = Marker_tyRef_5Red8qNVEd2T0lGUaDPoZA;
NTI_RQ9cbM0iZgecIlTaA8WAEPA_.size = sizeof(tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA);
NTI_RQ9cbM0iZgecIlTaA8WAEPA_.kind = 17;
NTI_RQ9cbM0iZgecIlTaA8WAEPA_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[29].len = 0; TM_9bZxUaTPy7yWEccQCxHXsww_0[29].kind = 2;
NTI_RQ9cbM0iZgecIlTaA8WAEPA_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[29];
NTI_IrNL59cXPnEUQVBLXMrTE9bA_.size = sizeof(tyObject_FailedToConnectException_RQ9cbM0iZgecIlTaA8WAEPA*);
NTI_IrNL59cXPnEUQVBLXMrTE9bA_.kind = 22;
NTI_IrNL59cXPnEUQVBLXMrTE9bA_.base = (&NTI_RQ9cbM0iZgecIlTaA8WAEPA_);
NTI_IrNL59cXPnEUQVBLXMrTE9bA_.marker = Marker_tyRef_IrNL59cXPnEUQVBLXMrTE9bA;
NTI_8L13g133N2Wr6SiGX9cn8nw_.size = sizeof(tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw);
NTI_8L13g133N2Wr6SiGX9cn8nw_.kind = 17;
NTI_8L13g133N2Wr6SiGX9cn8nw_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[30].len = 0; TM_9bZxUaTPy7yWEccQCxHXsww_0[30].kind = 2;
NTI_8L13g133N2Wr6SiGX9cn8nw_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[30];
NTI_mNHHdog9chWGG2MSH2CNqXQ_.size = sizeof(tyObject_InvalidConfigurationException_8L13g133N2Wr6SiGX9cn8nw*);
NTI_mNHHdog9chWGG2MSH2CNqXQ_.kind = 22;
NTI_mNHHdog9chWGG2MSH2CNqXQ_.base = (&NTI_8L13g133N2Wr6SiGX9cn8nw_);
NTI_mNHHdog9chWGG2MSH2CNqXQ_.marker = Marker_tyRef_mNHHdog9chWGG2MSH2CNqXQ;
NTI_9c4fposUbks0zxNVErgCzDA_.size = sizeof(tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA);
NTI_9c4fposUbks0zxNVErgCzDA_.kind = 17;
NTI_9c4fposUbks0zxNVErgCzDA_.base = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
TM_9bZxUaTPy7yWEccQCxHXsww_0[31].len = 0; TM_9bZxUaTPy7yWEccQCxHXsww_0[31].kind = 2;
NTI_9c4fposUbks0zxNVErgCzDA_.node = &TM_9bZxUaTPy7yWEccQCxHXsww_0[31];
NTI_4gdZvN5gFqFdHFTecosQ6A_.size = sizeof(tyObject_MissingConfigFile_9c4fposUbks0zxNVErgCzDA*);
NTI_4gdZvN5gFqFdHFTecosQ6A_.kind = 22;
NTI_4gdZvN5gFqFdHFTecosQ6A_.base = (&NTI_9c4fposUbks0zxNVErgCzDA_);
NTI_4gdZvN5gFqFdHFTecosQ6A_.marker = Marker_tyRef_4gdZvN5gFqFdHFTecosQ6A;
}

