/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/ryan/.choosenim/toolchains/nim-0.18.0/lib -o /home/ryan/dev/slackbot/src/nimcache/stdlib_securehash.o /home/ryan/dev/slackbot/src/nimcache/stdlib_securehash.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 tyArray_YtcvxHNKV4YiecPE9ap1mcA[20];
typedef NU32 tyArray_xsE8WL1yT5DKfrMdYB89bYA[5];
typedef NU32 tyArray_BhDmUZcWSpYFIy5J8Xi8mQ[80];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(void, init_1FhlX6i1LE6EQdyY79bMZ6A)(NU32* result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, innerHash_zaIrNw9b9b0rKA9c6mi2NyudA)(NU32* state, NU32* w);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, sha1_7wQ07XxB49cQVmHre59bNftw)(NCSTRING src, NI len, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, sha1_9aTd6QKIPh47P9cab3MQ58pg)(NimStringDesc* src, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result);
N_LIB_PRIVATE N_NIMCALL(void, secureHash_iXA7ojfe1syFxhtO0guLpg)(NimStringDesc* str, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result);
N_LIB_PRIVATE N_NIMCALL(void, secureHashFile_WH9bD1JrTXe4j39astgya4oA)(NimStringDesc* filename, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readFile_T9cm5LIRX2tKEH9aREBZ8A0w)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__At9aCTfZ0LzVIMgxCh2oK7g)(tyArray_YtcvxHNKV4YiecPE9ap1mcA self);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, parseSecureHash_z6ogq7oeMr7FogkL734yew)(NimStringDesc* hash, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result);
N_LIB_PRIVATE N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__D9cw7Ut67uVRyWe3YecX0SQ)(tyArray_YtcvxHNKV4YiecPE9ap1mcA a, tyArray_YtcvxHNKV4YiecPE9ap1mcA b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__Ql5vZ51gew5fqwplIYujaw)(tyArray_YtcvxHNKV4YiecPE9ap1mcA x, tyArray_YtcvxHNKV4YiecPE9ap1mcA y);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ_;
TNimType NTI_YtcvxHNKV4YiecPE9ap1mcA_;
STRING_LITERAL(TM_vvZ67p0IGcFrRHVAevBkPw_52, "", 0);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, init_1FhlX6i1LE6EQdyY79bMZ6A)(NU32* result) {
	nimfr_("init", "sha1.nim");
	nimln_(53, "sha1.nim");
	result[(((NI) 0))- 0] = ((NU32) 1732584193);
	nimln_(54, "sha1.nim");
	result[(((NI) 1))- 0] = ((NU32) IL64(4023233417));
	nimln_(55, "sha1.nim");
	result[(((NI) 2))- 0] = ((NU32) IL64(2562383102));
	nimln_(56, "sha1.nim");
	result[(((NI) 3))- 0] = ((NU32) 271733878);
	nimln_(57, "sha1.nim");
	result[(((NI) 4))- 0] = ((NU32) IL64(3285377520));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, innerHash_zaIrNw9b9b0rKA9c6mi2NyudA)(NU32* state, NU32* w) {
	NU32 a;
	NU32 b;
	NU32 c;
	NU32 d;
	NU32 e;
	NI round_1;
	NU32 v;
	NU32 v_2;
	NU32 v_3;
	NU32 v_4;
	NU32 v_5;
	nimfr_("innerHash", "sha1.nim");
	nimln_(61, "sha1.nim");
	a = state[(((NI) 0))- 0];
	nimln_(62, "sha1.nim");
	b = state[(((NI) 1))- 0];
	nimln_(63, "sha1.nim");
	c = state[(((NI) 2))- 0];
	nimln_(64, "sha1.nim");
	d = state[(((NI) 3))- 0];
	nimln_(65, "sha1.nim");
	e = state[(((NI) 4))- 0];
	nimln_(67, "sha1.nim");
	round_1 = ((NI) 0);
	{
		nimln_(89, "sha1.nim");
		while (1) {
			NU32 t;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_2;
			if (!(round_1 < ((NI) 16))) goto LA2;
			nimln_(73, "sha1.nim");
			nimln_(70, "sha1.nim");
			nimln_(73, "sha1.nim");
			nimln_(90, "sha1.nim");
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			t = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(a) << (NU64)(((NI) 5))) | (NU32)((NU32)(a) >> (NU32)(((NU32) 27))))) + (NU32)((NU32)((NU32)(b & c) | (NU32)((NU32)((NU32) ~(b)) & d))))) + (NU32)(e))) + (NU32)(((NU32) 1518500249)))) + (NU32)(w[(round_1)- 0]));
			nimln_(74, "sha1.nim");
			e = d;
			nimln_(75, "sha1.nim");
			d = c;
			nimln_(70, "sha1.nim");
			nimln_(76, "sha1.nim");
			c = (NU32)((NU32)((NU64)(b) << (NU64)(((NI) 30))) | (NU32)((NU32)(b) >> (NU32)(((NU32) 2))));
			nimln_(77, "sha1.nim");
			b = a;
			nimln_(78, "sha1.nim");
			a = t;
			nimln_(91, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_2 = addInt(round_1, ((NI) 1));
			round_1 = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_2);
		} LA2: ;
	}
	{
		nimln_(93, "sha1.nim");
		while (1) {
			NI TM_vvZ67p0IGcFrRHVAevBkPw_3;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_4;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_5;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_6;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_7;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_8;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_9;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_10;
			NU32 t_2;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_11;
			if (!(round_1 < ((NI) 20))) goto LA4;
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			nimln_(70, "sha1.nim");
			nimln_(81, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_3 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_3)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_4 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_4)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_5 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_5)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_6 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_6)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_7 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_7)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_8 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_8)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_9 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_9)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_10 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_10)) > (NU)(79)) raiseIndexError();
			w[(round_1)- 0] = (NU32)((NU32)((NU64)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_3))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_4))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_5))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_6))- 0])) << (NU64)(((NI) 1))) | (NU32)((NU32)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_7))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_8))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_9))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_10))- 0])) >> (NU32)(((NU32) 31))));
			nimln_(73, "sha1.nim");
			nimln_(70, "sha1.nim");
			nimln_(73, "sha1.nim");
			nimln_(95, "sha1.nim");
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			t_2 = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(a) << (NU64)(((NI) 5))) | (NU32)((NU32)(a) >> (NU32)(((NU32) 27))))) + (NU32)((NU32)((NU32)(b & c) | (NU32)((NU32)((NU32) ~(b)) & d))))) + (NU32)(e))) + (NU32)(((NU32) 1518500249)))) + (NU32)(w[(round_1)- 0]));
			nimln_(74, "sha1.nim");
			e = d;
			nimln_(75, "sha1.nim");
			d = c;
			nimln_(70, "sha1.nim");
			nimln_(76, "sha1.nim");
			c = (NU32)((NU32)((NU64)(b) << (NU64)(((NI) 30))) | (NU32)((NU32)(b) >> (NU32)(((NU32) 2))));
			nimln_(77, "sha1.nim");
			b = a;
			nimln_(78, "sha1.nim");
			a = t_2;
			nimln_(83, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_11 = addInt(round_1, ((NI) 1));
			round_1 = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_11);
		} LA4: ;
	}
	{
		nimln_(97, "sha1.nim");
		while (1) {
			NI TM_vvZ67p0IGcFrRHVAevBkPw_12;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_13;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_14;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_15;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_16;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_17;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_18;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_19;
			NU32 t_3;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_20;
			if (!(round_1 < ((NI) 40))) goto LA6;
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			nimln_(70, "sha1.nim");
			nimln_(81, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_12 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_12)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_13 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_13)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_14 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_14)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_15 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_15)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_16 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_16)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_17 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_17)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_18 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_18)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_19 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_19)) > (NU)(79)) raiseIndexError();
			w[(round_1)- 0] = (NU32)((NU32)((NU64)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_12))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_13))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_14))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_15))- 0])) << (NU64)(((NI) 1))) | (NU32)((NU32)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_16))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_17))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_18))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_19))- 0])) >> (NU32)(((NU32) 31))));
			nimln_(73, "sha1.nim");
			nimln_(70, "sha1.nim");
			nimln_(73, "sha1.nim");
			nimln_(99, "sha1.nim");
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			t_3 = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(a) << (NU64)(((NI) 5))) | (NU32)((NU32)(a) >> (NU32)(((NU32) 27))))) + (NU32)((NU32)((NU32)(b ^ c) ^ d)))) + (NU32)(e))) + (NU32)(((NU32) 1859775393)))) + (NU32)(w[(round_1)- 0]));
			nimln_(74, "sha1.nim");
			e = d;
			nimln_(75, "sha1.nim");
			d = c;
			nimln_(70, "sha1.nim");
			nimln_(76, "sha1.nim");
			c = (NU32)((NU32)((NU64)(b) << (NU64)(((NI) 30))) | (NU32)((NU32)(b) >> (NU32)(((NU32) 2))));
			nimln_(77, "sha1.nim");
			b = a;
			nimln_(78, "sha1.nim");
			a = t_3;
			nimln_(83, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_20 = addInt(round_1, ((NI) 1));
			round_1 = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_20);
		} LA6: ;
	}
	{
		nimln_(101, "sha1.nim");
		while (1) {
			NI TM_vvZ67p0IGcFrRHVAevBkPw_21;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_22;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_23;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_24;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_25;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_26;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_27;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_28;
			NU32 t_4;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_29;
			if (!(round_1 < ((NI) 60))) goto LA8;
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			nimln_(70, "sha1.nim");
			nimln_(81, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_21 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_21)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_22 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_22)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_23 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_23)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_24 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_24)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_25 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_25)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_26 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_26)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_27 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_27)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_28 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_28)) > (NU)(79)) raiseIndexError();
			w[(round_1)- 0] = (NU32)((NU32)((NU64)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_21))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_22))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_23))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_24))- 0])) << (NU64)(((NI) 1))) | (NU32)((NU32)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_25))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_26))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_27))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_28))- 0])) >> (NU32)(((NU32) 31))));
			nimln_(73, "sha1.nim");
			nimln_(70, "sha1.nim");
			nimln_(73, "sha1.nim");
			nimln_(103, "sha1.nim");
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			t_4 = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(a) << (NU64)(((NI) 5))) | (NU32)((NU32)(a) >> (NU32)(((NU32) 27))))) + (NU32)((NU32)((NU32)((NU32)(b & c) | (NU32)(b & d)) | (NU32)(c & d))))) + (NU32)(e))) + (NU32)(((NU32) IL64(2400959708))))) + (NU32)(w[(round_1)- 0]));
			nimln_(74, "sha1.nim");
			e = d;
			nimln_(75, "sha1.nim");
			d = c;
			nimln_(70, "sha1.nim");
			nimln_(76, "sha1.nim");
			c = (NU32)((NU32)((NU64)(b) << (NU64)(((NI) 30))) | (NU32)((NU32)(b) >> (NU32)(((NU32) 2))));
			nimln_(77, "sha1.nim");
			b = a;
			nimln_(78, "sha1.nim");
			a = t_4;
			nimln_(83, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_29 = addInt(round_1, ((NI) 1));
			round_1 = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_29);
		} LA8: ;
	}
	{
		nimln_(105, "sha1.nim");
		while (1) {
			NI TM_vvZ67p0IGcFrRHVAevBkPw_30;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_31;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_32;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_33;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_34;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_35;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_36;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_37;
			NU32 t_5;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_38;
			if (!(round_1 < ((NI) 80))) goto LA10;
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			nimln_(70, "sha1.nim");
			nimln_(81, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_30 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_30)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_31 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_31)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_32 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_32)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_33 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_33)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_34 = subInt(round_1, ((NI) 3));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_34)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_35 = subInt(round_1, ((NI) 8));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_35)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_36 = subInt(round_1, ((NI) 14));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_36)) > (NU)(79)) raiseIndexError();
			TM_vvZ67p0IGcFrRHVAevBkPw_37 = subInt(round_1, ((NI) 16));
			if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_37)) > (NU)(79)) raiseIndexError();
			w[(round_1)- 0] = (NU32)((NU32)((NU64)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_30))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_31))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_32))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_33))- 0])) << (NU64)(((NI) 1))) | (NU32)((NU32)((NU32)((NU32)((NU32)(w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_34))- 0] ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_35))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_36))- 0]) ^ w[((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_37))- 0])) >> (NU32)(((NU32) 31))));
			nimln_(73, "sha1.nim");
			nimln_(70, "sha1.nim");
			nimln_(73, "sha1.nim");
			nimln_(107, "sha1.nim");
			if ((NU)(round_1) > (NU)(79)) raiseIndexError();
			t_5 = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU64)(a) << (NU64)(((NI) 5))) | (NU32)((NU32)(a) >> (NU32)(((NU32) 27))))) + (NU32)((NU32)((NU32)(b ^ c) ^ d)))) + (NU32)(e))) + (NU32)(((NU32) IL64(3395469782))))) + (NU32)(w[(round_1)- 0]));
			nimln_(74, "sha1.nim");
			e = d;
			nimln_(75, "sha1.nim");
			d = c;
			nimln_(70, "sha1.nim");
			nimln_(76, "sha1.nim");
			c = (NU32)((NU32)((NU64)(b) << (NU64)(((NI) 30))) | (NU32)((NU32)(b) >> (NU32)(((NU32) 2))));
			nimln_(77, "sha1.nim");
			b = a;
			nimln_(78, "sha1.nim");
			a = t_5;
			nimln_(83, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_38 = addInt(round_1, ((NI) 1));
			round_1 = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_38);
		} LA10: ;
	}
	nimln_(86, "sha1.nim");
	nimln_(109, "sha1.nim");
	v = (NU32)((NU32)(state[(((NI) 0))- 0]) + (NU32)(a));
	nimln_(87, "sha1.nim");
	state[(((NI) 0))- 0] = v;
	nimln_(86, "sha1.nim");
	nimln_(110, "sha1.nim");
	v_2 = (NU32)((NU32)(state[(((NI) 1))- 0]) + (NU32)(b));
	nimln_(87, "sha1.nim");
	state[(((NI) 1))- 0] = v_2;
	nimln_(86, "sha1.nim");
	nimln_(111, "sha1.nim");
	v_3 = (NU32)((NU32)(state[(((NI) 2))- 0]) + (NU32)(c));
	nimln_(87, "sha1.nim");
	state[(((NI) 2))- 0] = v_3;
	nimln_(86, "sha1.nim");
	nimln_(112, "sha1.nim");
	v_4 = (NU32)((NU32)(state[(((NI) 3))- 0]) + (NU32)(d));
	nimln_(87, "sha1.nim");
	state[(((NI) 3))- 0] = v_4;
	nimln_(86, "sha1.nim");
	nimln_(113, "sha1.nim");
	v_5 = (NU32)((NU32)(state[(((NI) 4))- 0]) + (NU32)(e));
	nimln_(87, "sha1.nim");
	state[(((NI) 4))- 0] = v_5;
	popFrame();
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

N_LIB_PRIVATE N_NIMCALL(void, sha1_7wQ07XxB49cQVmHre59bNftw)(NCSTRING src, NI len, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result) {
	tyArray_xsE8WL1yT5DKfrMdYB89bYA state;
	tyArray_BhDmUZcWSpYFIy5J8Xi8mQ w;
	NI byteLen;
	NI endOfFullBlocks;
	NI TM_vvZ67p0IGcFrRHVAevBkPw_39;
	NI endCurrentBlock;
	NI currentBlock;
	NI TM_vvZ67p0IGcFrRHVAevBkPw_46;
	NI lastBlockBytes;
	nimfr_("sha1", "sha1.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	memset((void*)state, 0, sizeof(state));
	nimln_(118, "sha1.nim");
	init_1FhlX6i1LE6EQdyY79bMZ6A(state);
	memset((void*)w, 0, sizeof(w));
	nimln_(124, "sha1.nim");
	byteLen = len;
	nimln_(125, "sha1.nim");
	TM_vvZ67p0IGcFrRHVAevBkPw_39 = subInt(byteLen, ((NI) 64));
	endOfFullBlocks = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_39);
	nimln_(126, "sha1.nim");
	endCurrentBlock = ((NI) 0);
	nimln_(127, "sha1.nim");
	currentBlock = ((NI) 0);
	{
		nimln_(129, "sha1.nim");
		while (1) {
			NI TM_vvZ67p0IGcFrRHVAevBkPw_40;
			NI i;
			if (!(currentBlock <= endOfFullBlocks)) goto LA2;
			nimln_(130, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_40 = addInt(currentBlock, ((NI) 64));
			endCurrentBlock = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_40);
			nimln_(132, "sha1.nim");
			i = ((NI) 0);
			{
				nimln_(133, "sha1.nim");
				while (1) {
					NI TM_vvZ67p0IGcFrRHVAevBkPw_41;
					NI TM_vvZ67p0IGcFrRHVAevBkPw_42;
					NI TM_vvZ67p0IGcFrRHVAevBkPw_43;
					NI TM_vvZ67p0IGcFrRHVAevBkPw_44;
					NI TM_vvZ67p0IGcFrRHVAevBkPw_45;
					if (!(currentBlock < endCurrentBlock)) goto LA4;
					if ((NU)(i) > (NU)(79)) raiseIndexError();
					nimln_(135, "sha1.nim");
					nimln_(134, "sha1.nim");
					TM_vvZ67p0IGcFrRHVAevBkPw_41 = addInt(currentBlock, ((NI) 3));
					nimln_(135, "sha1.nim");
					TM_vvZ67p0IGcFrRHVAevBkPw_42 = addInt(currentBlock, ((NI) 2));
					nimln_(136, "sha1.nim");
					TM_vvZ67p0IGcFrRHVAevBkPw_43 = addInt(currentBlock, ((NI) 1));
					nimln_(137, "sha1.nim");
					w[(i)- 0] = (NU32)((NU32)((NU32)(((NU32) (((NU8)(src[(NI)(TM_vvZ67p0IGcFrRHVAevBkPw_41)])))) | (NU32)((NU32)(((NU32) (((NU8)(src[(NI)(TM_vvZ67p0IGcFrRHVAevBkPw_42)]))))) << (NU32)(((NU32) 8)))) | (NU32)((NU32)(((NU32) (((NU8)(src[(NI)(TM_vvZ67p0IGcFrRHVAevBkPw_43)]))))) << (NU32)(((NU32) 16)))) | (NU32)((NU32)(((NU32) (((NU8)(src[currentBlock]))))) << (NU32)(((NU32) 24))));
					nimln_(138, "sha1.nim");
					TM_vvZ67p0IGcFrRHVAevBkPw_44 = addInt(currentBlock, ((NI) 4));
					currentBlock = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_44);
					nimln_(139, "sha1.nim");
					TM_vvZ67p0IGcFrRHVAevBkPw_45 = addInt(i, ((NI) 1));
					i = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_45);
				} LA4: ;
			}
			nimln_(141, "sha1.nim");
			innerHash_zaIrNw9b9b0rKA9c6mi2NyudA(state, w);
		} LA2: ;
	}
	nimln_(144, "sha1.nim");
	TM_vvZ67p0IGcFrRHVAevBkPw_46 = subInt(byteLen, currentBlock);
	endCurrentBlock = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_46);
	nimln_(145, "sha1.nim");
	zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) (w)), ((NI) 64));
	nimln_(146, "sha1.nim");
	lastBlockBytes = ((NI) 0);
	{
		nimln_(148, "sha1.nim");
		while (1) {
			NU32 value;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_47;
			NI TM_vvZ67p0IGcFrRHVAevBkPw_48;
			if (!(lastBlockBytes < endCurrentBlock)) goto LA6;
			nimln_(150, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_47 = addInt(lastBlockBytes, currentBlock);
			nimln_(151, "sha1.nim");
			value = (NU32)((NU32)(((NU32) (((NU8)(src[(NI)(TM_vvZ67p0IGcFrRHVAevBkPw_47)]))))) << (NU32)((NU32)((NU64)((NU32)((NU32)(((NU32) 3)) - (NU32)(((NU32) ((NI)(lastBlockBytes & ((NI) 3))))))) << (NU64)(((NI) 3)))));
			nimln_(153, "sha1.nim");
			if ((NU)((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2)))) > (NU)(79)) raiseIndexError();
			if ((NU)((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2)))) > (NU)(79)) raiseIndexError();
			w[((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2))))- 0] = (NU32)(w[((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2))))- 0] | value);
			nimln_(154, "sha1.nim");
			TM_vvZ67p0IGcFrRHVAevBkPw_48 = addInt(lastBlockBytes, ((NI) 1));
			lastBlockBytes = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_48);
		} LA6: ;
	}
	nimln_(156, "sha1.nim");
	if ((NU)((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2)))) > (NU)(79)) raiseIndexError();
	if ((NU)((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2)))) > (NU)(79)) raiseIndexError();
	nimln_(157, "sha1.nim");
	w[((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2))))- 0] = (NU32)(w[((NI)((NU64)(lastBlockBytes) >> (NU64)(((NI) 2))))- 0] | (NU32)((NU32)(((NU32) 128)) << (NU32)((NU32)((NU64)((NU32)((NU32)(((NU32) 3)) - (NU32)(((NU32) ((NI)(lastBlockBytes & ((NI) 3))))))) << (NU64)(((NI) 3))))));
	nimln_(160, "sha1.nim");
	{
		if (!(((NI) 56) <= endCurrentBlock)) goto LA9_;
		nimln_(161, "sha1.nim");
		innerHash_zaIrNw9b9b0rKA9c6mi2NyudA(state, w);
		nimln_(162, "sha1.nim");
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) (w)), ((NI) 64));
	}
	LA9_: ;
	nimln_(164, "sha1.nim");
	w[(((NI) 15))- 0] = (NU32)((NU64)(((NU32) (byteLen))) << (NU64)(((NI) 3)));
	nimln_(165, "sha1.nim");
	innerHash_zaIrNw9b9b0rKA9c6mi2NyudA(state, w);
	{
		NI i_2;
		NI res;
		i_2 = (NI)0;
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_vvZ67p0IGcFrRHVAevBkPw_49;
				NI TM_vvZ67p0IGcFrRHVAevBkPw_50;
				NI TM_vvZ67p0IGcFrRHVAevBkPw_51;
				if (!(res <= ((NI) 19))) goto LA13;
				nimln_(2047, "system.nim");
				i_2 = res;
				if ((NU)(i_2) > (NU)(19)) raiseIndexError();
				nimln_(170, "sha1.nim");
				if ((NU)((NI)((NU64)(i_2) >> (NU64)(((NI) 2)))) > (NU)(4)) raiseIndexError();
				TM_vvZ67p0IGcFrRHVAevBkPw_49 = subInt(((NI) 3), (NI)(i_2 & ((NI) 3)));
				TM_vvZ67p0IGcFrRHVAevBkPw_50 = mulInt((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_49), ((NI) 8));
				Result[(i_2)- 0] = ((NU8) ((NI)((NI)((NU64)(((NI) (state[((NI)((NU64)(i_2) >> (NU64)(((NI) 2))))- 0]))) >> (NU64)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_50))) & ((NI) 255))));
				nimln_(2048, "system.nim");
				TM_vvZ67p0IGcFrRHVAevBkPw_51 = addInt(res, ((NI) 1));
				res = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_51);
			} LA13: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, sha1_9aTd6QKIPh47P9cab3MQ58pg)(NimStringDesc* src, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result) {
	nimfr_("sha1", "sha1.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(173, "sha1.nim");
	nimln_(174, "sha1.nim");
	sha1_7wQ07XxB49cQVmHre59bNftw(src->data, (src ? src->Sup.len : 0), Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, secureHash_iXA7ojfe1syFxhtO0guLpg)(NimStringDesc* str, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result) {
	nimfr_("secureHash", "sha1.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(176, "sha1.nim");
	sha1_9aTd6QKIPh47P9cab3MQ58pg(str, Result);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, secureHashFile_WH9bD1JrTXe4j39astgya4oA)(NimStringDesc* filename, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result) {
	NimStringDesc* T1_;
	nimfr_("secureHashFile", "sha1.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	nimln_(177, "sha1.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = readFile_T9cm5LIRX2tKEH9aREBZ8A0w(filename);
	secureHash_iXA7ojfe1syFxhtO0guLpg(T1_, Result);
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__At9aCTfZ0LzVIMgxCh2oK7g)(tyArray_YtcvxHNKV4YiecPE9ap1mcA self) {
	NimStringDesc* result;
	nimfr_("$", "sha1.nim");
	result = (NimStringDesc*)0;
	nimln_(179, "sha1.nim");
	result = copyString(((NimStringDesc*) &TM_vvZ67p0IGcFrRHVAevBkPw_52));
	{
		NU8 v;
		tyArray_YtcvxHNKV4YiecPE9ap1mcA colontmp_;
		NI i;
		v = (NU8)0;
		memset((void*)colontmp_, 0, sizeof(colontmp_));
		nimln_(180, "sha1.nim");
		memcpy((void*)colontmp_, (NIM_CONST void*)self, sizeof(tyArray_YtcvxHNKV4YiecPE9ap1mcA));
		nimln_(2199, "system.nim");
		i = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 19))) goto LA4_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NimStringDesc* T8_;
					NI TM_vvZ67p0IGcFrRHVAevBkPw_53;
					nimln_(2202, "system.nim");
					v = colontmp_[(i)- 0];
					nimln_(181, "sha1.nim");
					T8_ = (NimStringDesc*)0;
					T8_ = nsuToHex(((NI64) (((NI) (v)))), ((NI) 2));
					result = resizeString(result, T8_->Sup.len + 0);
appendString(result, T8_);
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 19) <= ((NI) (i)))) goto LA11_;
						goto LA6;
					}
					LA11_: ;
					nimln_(2204, "system.nim");
					TM_vvZ67p0IGcFrRHVAevBkPw_53 = addInt(i, ((NI) 1));
					if (TM_vvZ67p0IGcFrRHVAevBkPw_53 < 0 || TM_vvZ67p0IGcFrRHVAevBkPw_53 > 19) raiseOverflow();
					i = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_53);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

N_LIB_PRIVATE N_NIMCALL(void, parseSecureHash_z6ogq7oeMr7FogkL734yew)(NimStringDesc* hash, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result) {
	nimfr_("parseSecureHash", "sha1.nim");
	chckNil((void*)Result);
	memset((void*)Result, 0, sizeof(Result));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NimStringDesc* T4_;
				NI TM_vvZ67p0IGcFrRHVAevBkPw_54;
				NI TM_vvZ67p0IGcFrRHVAevBkPw_55;
				NI TM_vvZ67p0IGcFrRHVAevBkPw_56;
				NI T5_;
				NI TM_vvZ67p0IGcFrRHVAevBkPw_57;
				if (!(i_2 < ((NI) 20))) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(19)) raiseIndexError();
				nimln_(185, "sha1.nim");
				T4_ = (NimStringDesc*)0;
				TM_vvZ67p0IGcFrRHVAevBkPw_54 = mulInt(i, ((NI) 2));
				if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_54)) > (NU)(hash->Sup.len)) raiseIndexError();
				TM_vvZ67p0IGcFrRHVAevBkPw_55 = mulInt(i, ((NI) 2));
				TM_vvZ67p0IGcFrRHVAevBkPw_56 = addInt((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_55), ((NI) 1));
				if ((NU)((NI)(TM_vvZ67p0IGcFrRHVAevBkPw_56)) > (NU)(hash->Sup.len)) raiseIndexError();
				T4_ = rawNewString(2);
appendChar(T4_, hash->data[(NI)(TM_vvZ67p0IGcFrRHVAevBkPw_54)]);
appendChar(T4_, hash->data[(NI)(TM_vvZ67p0IGcFrRHVAevBkPw_56)]);
				T5_ = (NI)0;
				T5_ = nsuParseHexInt(T4_);
				Result[(i)- 0] = ((NU8) (T5_));
				nimln_(3522, "system.nim");
				TM_vvZ67p0IGcFrRHVAevBkPw_57 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_vvZ67p0IGcFrRHVAevBkPw_57);
			} LA3: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__D9cw7Ut67uVRyWe3YecX0SQ)(tyArray_YtcvxHNKV4YiecPE9ap1mcA a, tyArray_YtcvxHNKV4YiecPE9ap1mcA b) {
	NIM_BOOL result;
	nimfr_("==", "sha1.nim");
	result = (NIM_BOOL)0;
	nimln_(189, "sha1.nim");
	result = eqeq__Ql5vZ51gew5fqwplIYujaw(a, b);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_securehashInit000)(void) {
	nimfr_("securehash", "securehash.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_securehashDatInit000)(void) {
NTI_YtcvxHNKV4YiecPE9ap1mcA_.size = sizeof(tyArray_YtcvxHNKV4YiecPE9ap1mcA);
NTI_YtcvxHNKV4YiecPE9ap1mcA_.kind = 16;
NTI_YtcvxHNKV4YiecPE9ap1mcA_.base = (&NTI_k3HXouOuhqAKq0dx450lXQ_);
NTI_YtcvxHNKV4YiecPE9ap1mcA_.flags = 3;
}

