/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/ryan/.choosenim/toolchains/nim-0.18.0/lib -o /home/ryan/dev/slackbot/src/nimcache/stdlib_options.o /home/ryan/dev/slackbot/src/nimcache/stdlib_options.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA;
typedef struct tyObject_Table_F9bs8SaMaWAqBNBzDdxGm9aw tyObject_Table_F9bs8SaMaWAqBNBzDdxGm9aw;
typedef struct tySequence_cHRu6hz8BbEXIRzqQBKj7Q tySequence_cHRu6hz8BbEXIRzqQBKj7Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_ygGvOeju7V9cYfwEZEiz1Dw tyTuple_ygGvOeju7V9cYfwEZEiz1Dw;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct RootObj RootObj;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ {
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val;
NIM_BOOL has;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_F9bs8SaMaWAqBNBzDdxGm9aw {
tySequence_cHRu6hz8BbEXIRzqQBKj7Q* data;
NI counter;
};
struct tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA {
tyObject_Table_F9bs8SaMaWAqBNBzDdxGm9aw val;
NIM_BOOL has;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_ygGvOeju7V9cYfwEZEiz1Dw {
NI Field0;
NI Field1;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* Field2;
};
struct RootObj {
TNimType* m_type;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
NimStringDesc* stackTrace;
NI id;
NimStringDesc* fromProc;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_cHRu6hz8BbEXIRzqQBKj7Q {
  TGenericSeq Sup;
  tyTuple_ygGvOeju7V9cYfwEZEiz1Dw data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_Q4RsUqhsTDIbkeIguPSpvA_2)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_2aXfJF9c9aud3h15Ro9cnHvig_2)(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA self);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_PTLHc2rN2qe9biS0jK9ambFA_;
extern TNimType NTI_F9bs8SaMaWAqBNBzDdxGm9aw_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_cHRu6hz8BbEXIRzqQBKj7Q_;
STRING_LITERAL(TM_4DNs4bMUkswhWc4o4dM9bbg_2, "isSome(self) ", 13);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, some_JMiA9ccATJp8JunIrSlndYA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val) {
	tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ result;
	nimfr_("some", "options.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(81, "options.nim");
	result.has = NIM_TRUE;
	nimln_(82, "options.nim");
	result.val = val;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, none_IBO7fiOVpMVOmhrZWFqq1A)(void) {
	tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ result;
	nimfr_("none", "options.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(86, "options.nim");
	result.has = NIM_FALSE;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_Q4RsUqhsTDIbkeIguPSpvA)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(92, "options.nim");
	result = !(self.has);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_Q4RsUqhsTDIbkeIguPSpvA_2)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(89, "options.nim");
	result = self.has;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, unsafeGet_fdGmwO5YUOWb8OBjkhgjng)(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ self) {
	tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg result;
	nimfr_("unsafeGet", "options.nim");
	result = (tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg)0;
	nimln_(95, "options.nim");
	nimln_(96, "options.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_Q4RsUqhsTDIbkeIguPSpvA_2(self);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_2));
	}
	LA4_: ;
	result = self.val;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_2aXfJF9c9aud3h15Ro9cnHvig)(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA self) {
	NIM_BOOL result;
	nimfr_("isNone", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(92, "options.nim");
	result = !(self.has);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, some_DooQCDFm9a9chLx1MHlPEsPA)(tyObject_Table_F9bs8SaMaWAqBNBzDdxGm9aw val, tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA* Result) {
	nimfr_("some", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_PTLHc2rN2qe9biS0jK9ambFA_));
	nimln_(81, "options.nim");
	(*Result).has = NIM_TRUE;
	nimln_(82, "options.nim");
	genericSeqAssign((&(*Result).val.data), val.data, (&NTI_cHRu6hz8BbEXIRzqQBKj7Q_));
	(*Result).val.counter = val.counter;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_2aXfJF9c9aud3h15Ro9cnHvig_2)(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(89, "options.nim");
	result = self.has;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, unsafeGet_mDykCWocOtcSw6r4DbOwww)(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA self, tyObject_Table_F9bs8SaMaWAqBNBzDdxGm9aw* Result) {
	nimfr_("unsafeGet", "options.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_F9bs8SaMaWAqBNBzDdxGm9aw_));
	nimln_(95, "options.nim");
	nimln_(96, "options.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_2aXfJF9c9aud3h15Ro9cnHvig_2(self);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4DNs4bMUkswhWc4o4dM9bbg_2));
	}
	LA4_: ;
	genericSeqAssign((&(*Result).data), self.val.data, (&NTI_cHRu6hz8BbEXIRzqQBKj7Q_));
	(*Result).counter = self.val.counter;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_optionsInit000)(void) {
	nimfr_("options", "options.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_optionsDatInit000)(void) {
static TNimNode* TM_4DNs4bMUkswhWc4o4dM9bbg_3[2];
static TNimNode TM_4DNs4bMUkswhWc4o4dM9bbg_0[3];
NTI_PTLHc2rN2qe9biS0jK9ambFA_.size = sizeof(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA);
NTI_PTLHc2rN2qe9biS0jK9ambFA_.kind = 18;
NTI_PTLHc2rN2qe9biS0jK9ambFA_.base = 0;
TM_4DNs4bMUkswhWc4o4dM9bbg_3[0] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[1];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].offset = offsetof(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA, val);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].typ = (&NTI_F9bs8SaMaWAqBNBzDdxGm9aw_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[1].name = "val";
TM_4DNs4bMUkswhWc4o4dM9bbg_3[1] = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[2];
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].kind = 1;
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].offset = offsetof(tyObject_Option_PTLHc2rN2qe9biS0jK9ambFA, has);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4DNs4bMUkswhWc4o4dM9bbg_0[2].name = "has";
TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].len = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].kind = 2; TM_4DNs4bMUkswhWc4o4dM9bbg_0[0].sons = &TM_4DNs4bMUkswhWc4o4dM9bbg_3[0];
NTI_PTLHc2rN2qe9biS0jK9ambFA_.node = &TM_4DNs4bMUkswhWc4o4dM9bbg_0[0];
}

