/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/ryan/.choosenim/toolchains/nim-0.18.0/lib -o /home/ryan/dev/slackbot/src/nimcache/websocket_server.o /home/ryan/dev/slackbot/src/nimcache/websocket_server.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg;
typedef struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ;
typedef struct tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg;
typedef struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA;
typedef struct tyTuple_kN8up2W6YKc5YA9avn5mV5w tyTuple_kN8up2W6YKc5YA9avn5mV5w;
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg;
typedef struct tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw;
typedef struct tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ;
typedef struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA;
typedef struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ;
typedef struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw;
typedef struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w;
typedef struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA tyObject_Table_LLQadDAXEvd71UDdEc3lDA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ;
typedef struct tySequence_8Np6tlClE5az1CyqZdN19bQ tySequence_8Np6tlClE5az1CyqZdN19bQ;
typedef struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw;
typedef struct tySequence_JiteSJxrvz63iP2o9bcn2Sg tySequence_JiteSJxrvz63iP2o9bcn2Sg;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
typedef struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ tyTuple_g1w83cyyBYiVU9c8WEJWnjQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyArray_YtcvxHNKV4YiecPE9ap1mcA[20];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA;
struct tyTuple_kN8up2W6YKc5YA9avn5mV5w {
NimStringDesc* Field0;
NI Field1;
NI Field2;
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ {
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* client;
tyEnum_HttpMethod_wfZHspwVKQPl9aWhkIcMrAA reqMethod;
tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers;
tyTuple_kN8up2W6YKc5YA9avn5mV5w protocol;
tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ url;
NimStringDesc* hostname;
NimStringDesc* body;
};
typedef struct {
N_NIMCALL_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_3cmVDZYspcmD9a16VGUFJoA;
struct tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw {
  RootObj Sup;
NI colonstate_;
tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ req1;
tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg* retFuture2;
NimStringDesc* protocol3;
tyProc_3cmVDZYspcmD9a16VGUFJoA nameIterVar4;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw {
tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw* Field0;
NimStringDesc* Field1;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ {
  RootObj Sup;
NI colonstate_;
tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw result1;
tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw* colonup_;
NIM_BOOL noProtocol3;
NimStringDesc* prot4;
NimStringDesc* it5;
NimStringDesc* colontmp6_;
NI last7;
NI splits8;
NI first9;
NimStringDesc* msg10;
tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future11;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg;
typedef NU8 tyEnum_SocketKind_LVqgZYstYjAJSuADJ9bp5XA;
struct tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw {
  RootObj Sup;
tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* sock;
NimStringDesc* protocol;
tyEnum_SocketKind_LVqgZYstYjAJSuADJ9bp5XA kind;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef long tyArray_TcvIiMAJvcwzNLsZkfnFnQ[25];
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, TM_4wr9busLgulMeCFBdHSvIuw_32) (void);
typedef N_CLOSURE_PTR(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, TM_4wr9busLgulMeCFBdHSvIuw_33) (void);
struct tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA {
  Exception Sup;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc_IIomJ6ptE6vfJ5zRbATgkQ;
typedef N_CLOSURE_PTR(void, TM_4wr9busLgulMeCFBdHSvIuw_35) (void);
struct tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ {
tyProc_IIomJ6ptE6vfJ5zRbATgkQ function;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ* next;
};
struct tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg {
  RootObj Sup;
tyObject_CallbackList_tKSBWiaJMWD3JZxwqg7UFQ callbacks;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorStackTrace;
NimStringDesc* stackTrace;
NI id;
NimStringDesc* fromProc;
};
struct tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw value;
};
typedef NIM_CHAR tyArray_QQGLPNVVwLhYjkngqAxXQQ[4001];
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg {
int fd;
NIM_BOOL closed;
NIM_BOOL isBuffered;
union{
struct {tyArray_QQGLPNVVwLhYjkngqAxXQQ buffer;
NI currPos;
NI bufLen;
} S1;
} isBufferedU;
NIM_BOOL isSsl;
union{
struct {tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* sslHandle;
tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w* sslContext;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioIn;
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* bioOut;
} S1;
} isSslU;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain;
tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType;
tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol;
};
struct tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA {
tyObject_Table_LLQadDAXEvd71UDdEc3lDA* table;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg {
  tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg Sup;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw {
char dummy;
};
struct tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ {
tySequence_8Np6tlClE5az1CyqZdN19bQ* data;
NI counter;
};
struct tyObject_SslContextcolonObjectType__nNdejAl9bbVbX7sP6RJ4h0w {
tyObject_SslStruct_hZKic6WnTBMq6Usbg49bnhw* context;
tyObject_HashSet_J1RbOJyRcRl1E5zDK6YKcQ referencedData;
tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw* extraInternal;
};
struct tyObject_Table_LLQadDAXEvd71UDdEc3lDA {
tySequence_JiteSJxrvz63iP2o9bcn2Sg* data;
NI counter;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* identity, void* ClE_0);
void* ClE_0;
} tyProc_lRW9cfxqfm1ql4gkxfLReYg;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NimStringDesc* hint, tyTuple_UV3llMMYFckfui8YMBuUZA* Result, void* ClE_0);
void* ClE_0;
} tyProc_nzIUHFubO43GG203VFo9b7A;
struct tyObject_SslContextExtraInternalcolonObjectType__QnsPmxexBDpqB7otv3E4Sw {
  RootObj Sup;
tyProc_lRW9cfxqfm1ql4gkxfLReYg serverGetPskFunc;
tyProc_nzIUHFubO43GG203VFo9b7A clientGetPskFunc;
};
struct tyTuple_g1w83cyyBYiVU9c8WEJWnjQ {
NI Field0;
NimStringDesc* Field1;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* Field2;
};
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
struct tySequence_JiteSJxrvz63iP2o9bcn2Sg {
  TGenericSeq Sup;
  tyTuple_g1w83cyyBYiVU9c8WEJWnjQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, makeHandshakeResponse_eRqpPEOg3sGrMOFQbu5WbQ)(NimStringDesc* key, NimStringDesc* protocol);
N_LIB_PRIVATE N_NIMCALL(void, secureHash_iXA7ojfe1syFxhtO0guLpg)(NimStringDesc* str, tyArray_YtcvxHNKV4YiecPE9ap1mcA Result);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encode_8tc7ShUv28tbkkCiLVvt1g)(NimStringDesc* s, NI lineLen, NimStringDesc* newLine);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeHex_lfVYv8z1eInCBADVgGvZWw)(NimStringDesc* str);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__At9aCTfZ0LzVIMgxCh2oK7g)(tyArray_YtcvxHNKV4YiecPE9ap1mcA self);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuIsNilOrEmpty)(NimStringDesc* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg*, verifyWebsocketRequest_fcA3f463uAvV9bTbiyyDV8w)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req, NimStringDesc* protocol);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_jyDW3skhKMaCr8hmgg44Pg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg*, newFuture_tn8LGE0sZTkiYNWWIOkQAQ)(NimStringDesc* fromProc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef_vFUUP2xqC6NqYC9cxtYPsoQ)(void* p, NI op);
N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, verifyWebsocketRequestIter_tzF9cEK9bDvzwAcUnBk9bNAXQ)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toString_lBEoN6A9bKNublZsSxuhYeA)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ* values);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, getOrDefault_iYU3axHYDC9bL2abC1Ss5fw)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key, tySequence_sM4lkSb7zS6F7OVMvW9cffQ* default_0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, complete_9cdCqj3ph8OkumBYITLkE2Q)(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg* future, tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw val);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_T0KkqFbqlm8065Ws4h4NSg)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__2I7W00Lgs3jqrdJTli4b9cA)(tyObject_HttpHeaderscolonObjectType__GM611pWlOrQ7hvMPcuAACA* headers, NimStringDesc* key);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuStrip)(NimStringDesc* s, NIM_BOOL leading, NIM_BOOL trailing, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg*, send_AqMRJAH66soP1Q6GLXU5LA)(tyObject_AsyncSocketDesc_D7quBEmo0QGfBsms9bXpWfg* socket, NimStringDesc* data, tySet_tyEnum_SocketFlag_4xio0cAXR7XG4pF9bVcpxEg flags);
N_LIB_PRIVATE N_NIMCALL(void, read_EYgDXwwneJeAEUfXLUHmhg)(tyObject_FuturecolonObjectType__SmxCgsot45ayPNDBegkWAg* future);
static N_INLINE(void, nimGCunrefRC1)(void* p);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_LIB_PRIVATE N_CLOSURE(void, verifyWebsocketRequest_continue_giCns6lOo9c9c8HtPb8uh1uw)(void* ClE_0);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch)(tyProc_3cmVDZYspcmD9a16VGUFJoA x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_ZDnEFECD9b9aKFsuVLxFyzkA_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, finished_ntBlpNGvne9cEZGeELSM9cOg)(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg* future);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatSingleElem)(NimStringDesc* formatstr, NimStringDesc* a);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, callbackeq__9c5z7ouO5bUylgKxaZoIuVg_2)(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* future, tyProc_IIomJ6ptE6vfJ5zRbATgkQ cb);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(void, fail_DC8NBOnruQLZx4YiAhYmtw)(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, checkFinished_wI775NGyTW8uIdYVC8nv4w)(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg* future);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_BLtPjr3JJTiIlIuaqlnxbw_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_1Wfxxtqzahm0R6lueM9aQmQ_;
TNimType NTI_S3HkVX1vbi9cJcN9b3B7gRkw_;
extern TNimType NTI_inAXQwjH33JjtLPhTcLm9cg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_kTAkTyBCGf7Dtp1iey59asg_;
extern TNimType NTI_3cmVDZYspcmD9a16VGUFJoA_;
TNimType NTI_jyDW3skhKMaCr8hmgg44Pg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_f7vzrmTkU1fEyae7tCDJHQ_;
extern TNimType NTI_Mpt8aZ13tT2AYV71yyfHcA_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_zXD0JrbeCNyAaW4E6fB9aqg_;
TNimType NTI_vFUUP2xqC6NqYC9cxtYPsoQ_;
extern TNimType NTI_FO7G9bZCP6FlKF64Vby7eGw_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_TmgWlPUbRr7iGD2UE1cu6A_;
extern TNimType NTI_8FC9arcap3s5ZtfMs75krtA_;
extern Exception* currException_9bVPeDJlYTi9bQApZpfH8wjg;
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_2, "258EAFA5-E914-47DA-95CA-C5AB0DC85B11", 36);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_3, "\015\012", 2);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_4, "HTTP/1.1 101 Web Socket Protocol Handshake\015\012", 44);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_5, "Sec-Websocket-Accept: ", 22);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_6, "Connection: Upgrade\015\012", 21);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_7, "Upgrade: websocket\015\012", 20);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_8, "Sec-Websocket-Protocol: ", 24);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_11, "verifyWebsocketRequest", 22);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_13, "sec-websocket-version", 21);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_15, "", 0);
NIM_CONST struct {
  TGenericSeq Sup;
  NimStringDesc* data[1];
} TM_4wr9busLgulMeCFBdHSvIuw_16 = {{1, 1}, {((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_15)}};
NIM_CONST tySequence_sM4lkSb7zS6F7OVMvW9cffQ* TM_4wr9busLgulMeCFBdHSvIuw_14 = ((tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)&TM_4wr9busLgulMeCFBdHSvIuw_16);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_17, "13", 2);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_18, "the only supported sec-websocket-version is 13", 46);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_19, "sec-websocket-key", 17);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_20, "no sec-websocket-key provided", 29);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_21, "sec-websocket-protocol", 22);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_22, "server does not support protocol negotation", 43);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_4wr9busLgulMeCFBdHSvIuw_25 = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_28, "no advertised protocol supported; server speaks `", 49);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_29, "`", 1);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_30, "no protocol advertised, but server demands `", 44);
STRING_LITERAL(TM_4wr9busLgulMeCFBdHSvIuw_34, "Async procedure ($1) yielded `nil`, are you await\'ing a `nil` F"
"uture\?", 69);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, makeHandshakeResponse_eRqpPEOg3sGrMOFQbu5WbQ)(NimStringDesc* key, NimStringDesc* protocol) {
	NimStringDesc* result;
	tyArray_YtcvxHNKV4YiecPE9ap1mcA sh;
	NimStringDesc* T1_;
	NimStringDesc* acceptKey;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	NimStringDesc* T4_;
	nimfr_("makeHandshakeResponse", "server.nim");
	result = (NimStringDesc*)0;
	memset((void*)sh, 0, sizeof(sh));
	nimln_(47, "server.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = rawNewString(key->Sup.len + 36);
appendString(T1_, key);
appendString(T1_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_2));
	secureHash_iXA7ojfe1syFxhtO0guLpg(T1_, sh);
	nimln_(48, "server.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = dollar__At9aCTfZ0LzVIMgxCh2oK7g(sh);
	T3_ = (NimStringDesc*)0;
	T3_ = decodeHex_lfVYv8z1eInCBADVgGvZWw(T2_);
	acceptKey = encode_8tc7ShUv28tbkkCiLVvt1g(T3_, ((NI) 75), ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_3));
	nimln_(50, "server.nim");
	result = copyString(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_4));
	nimln_(51, "server.nim");
	T4_ = (NimStringDesc*)0;
	T4_ = rawNewString(acceptKey->Sup.len + 24);
appendString(T4_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_5));
appendString(T4_, acceptKey);
appendString(T4_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_3));
	result = resizeString(result, T4_->Sup.len + 0);
appendString(result, T4_);
	nimln_(52, "server.nim");
	result = resizeString(result, 21);
appendString(result, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_6));
	nimln_(53, "server.nim");
	result = resizeString(result, 20);
appendString(result, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_7));
	nimln_(54, "server.nim");
	{
		NIM_BOOL T7_;
		NimStringDesc* T10_;
		T7_ = (NIM_BOOL)0;
		T7_ = nsuIsNilOrEmpty(protocol);
		if (!!(T7_)) goto LA8_;
		nimln_(55, "server.nim");
		T10_ = (NimStringDesc*)0;
		T10_ = rawNewString(protocol->Sup.len + 26);
appendString(T10_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_8));
appendString(T10_, protocol);
appendString(T10_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_3));
		result = resizeString(result, T10_->Sup.len + 0);
appendString(result, T10_);
	}
	LA8_: ;
	nimln_(56, "server.nim");
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_3));
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_jyDW3skhKMaCr8hmgg44Pg)(void* p, NI op) {
	tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw* a;
	a = (tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw*)p;
	nimGCvisit((void*)(*a).req1.client, op);
	nimGCvisit((void*)(*a).req1.headers, op);
	nimGCvisit((void*)(*a).req1.protocol.Field0, op);
	nimGCvisit((void*)(*a).req1.url.scheme, op);
	nimGCvisit((void*)(*a).req1.url.username, op);
	nimGCvisit((void*)(*a).req1.url.password, op);
	nimGCvisit((void*)(*a).req1.url.hostname, op);
	nimGCvisit((void*)(*a).req1.url.port, op);
	nimGCvisit((void*)(*a).req1.url.path, op);
	nimGCvisit((void*)(*a).req1.url.query, op);
	nimGCvisit((void*)(*a).req1.url.anchor, op);
	nimGCvisit((void*)(*a).req1.hostname, op);
	nimGCvisit((void*)(*a).req1.body, op);
	nimGCvisit((void*)(*a).retFuture2, op);
	nimGCvisit((void*)(*a).protocol3, op);
	nimGCvisit((void*)(*a).nameIterVar4.ClE_0, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_vFUUP2xqC6NqYC9cxtYPsoQ)(void* p, NI op) {
	tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ* a;
	a = (tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ*)p;
	nimGCvisit((void*)(*a).result1.Field0, op);
	nimGCvisit((void*)(*a).result1.Field1, op);
	nimGCvisit((void*)(*a).colonup_, op);
	nimGCvisit((void*)(*a).prot4, op);
	nimGCvisit((void*)(*a).it5, op);
	nimGCvisit((void*)(*a).colontmp6_, op);
	nimGCvisit((void*)(*a).msg10, op);
	nimGCvisit((void*)(*a).future11, op);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

N_LIB_PRIVATE N_CLOSURE(tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*, verifyWebsocketRequestIter_tzF9cEK9bDvzwAcUnBk9bNAXQ)(void* ClE_0) {
	tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* result;
	tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ* colonenvP_;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T52_;
	NimStringDesc* T53_;
	NimStringDesc* T54_;
	NimStringDesc* T55_;
	nimfr_("verifyWebsocketRequestIter", "asyncmacro.nim");
{	result = (tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg*)0;
	colonenvP_ = (tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ*) ClE_0;
	switch ((*colonenvP_).colonstate_) {
	case -1: goto BeforeRet_;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	nimln_(85, "server.nim");
	{
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T3_;
		NimStringDesc* T4_;
		NimStringDesc* T7_;
		nimln_(398, "system.nim");
		nimln_(85, "server.nim");
		T3_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		T3_ = getOrDefault_iYU3axHYDC9bL2abC1Ss5fw((*(*colonenvP_).colonup_).req1.headers, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_13), TM_4wr9busLgulMeCFBdHSvIuw_14);
		T4_ = (NimStringDesc*)0;
		T4_ = toString_lBEoN6A9bKNublZsSxuhYeA(T3_);
		if (!!(eqStrings(T4_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_17)))) goto LA5_;
		nimln_(86, "server.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = (*colonenvP_).result1.Field1; (*colonenvP_).result1.Field1 = copyStringRC1(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_18));
		if (T7_) nimGCunrefNoCycle(T7_);
		nimln_(343, "asyncmacro.nim");
		complete_9cdCqj3ph8OkumBYITLkE2Q((*(*colonenvP_).colonup_).retFuture2, (*colonenvP_).result1);
		(*colonenvP_).colonstate_ = ((NI) -1);
		nimln_(80, "server.nim");
		nimln_(1157, "os.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(88, "server.nim");
	{
		NIM_BOOL T10_;
		NimStringDesc* T13_;
		T10_ = (NIM_BOOL)0;
		T10_ = hasKey_T0KkqFbqlm8065Ws4h4NSg((*(*colonenvP_).colonup_).req1.headers, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_19));
		if (!!(T10_)) goto LA11_;
		nimln_(89, "server.nim");
		T13_ = (NimStringDesc*)0;
		T13_ = (*colonenvP_).result1.Field1; (*colonenvP_).result1.Field1 = copyStringRC1(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_20));
		if (T13_) nimGCunrefNoCycle(T13_);
		nimln_(343, "asyncmacro.nim");
		complete_9cdCqj3ph8OkumBYITLkE2Q((*(*colonenvP_).colonup_).retFuture2, (*colonenvP_).result1);
		(*colonenvP_).colonstate_ = ((NI) -1);
		nimln_(80, "server.nim");
		nimln_(1157, "os.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	LA11_: ;
	nimln_(91, "server.nim");
	(*colonenvP_).noProtocol3 = nsuIsNilOrEmpty((*(*colonenvP_).colonup_).protocol3);
	nimln_(93, "server.nim");
	{
		NIM_BOOL T16_;
		T16_ = (NIM_BOOL)0;
		T16_ = hasKey_T0KkqFbqlm8065Ws4h4NSg((*(*colonenvP_).colonup_).req1.headers, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_21));
		if (!T16_) goto LA17_;
		nimln_(94, "server.nim");
		{
			NimStringDesc* T23_;
			if (!(*colonenvP_).noProtocol3) goto LA21_;
			nimln_(95, "server.nim");
			T23_ = (NimStringDesc*)0;
			T23_ = (*colonenvP_).result1.Field1; (*colonenvP_).result1.Field1 = copyStringRC1(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_22));
			if (T23_) nimGCunrefNoCycle(T23_);
			nimln_(343, "asyncmacro.nim");
			complete_9cdCqj3ph8OkumBYITLkE2Q((*(*colonenvP_).colonup_).retFuture2, (*colonenvP_).result1);
			(*colonenvP_).colonstate_ = ((NI) -1);
			nimln_(80, "server.nim");
			nimln_(1157, "os.nim");
			result = NIM_NIL;
			goto BeforeRet_;
		}
		LA21_: ;
		{
			NimStringDesc* T47_;
			nimln_(98, "server.nim");
			asgnRefNoCycle((void**) (&(*colonenvP_).prot4), nsuToLowerAsciiStr((*(*colonenvP_).colonup_).protocol3));
			{
				tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T26_;
				nimln_(100, "server.nim");
				T26_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
				T26_ = X5BX5D__2I7W00Lgs3jqrdJTli4b9cA((*(*colonenvP_).colonup_).req1.headers, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_21));
				asgnRefNoCycle((void**) (&(*colonenvP_).colontmp6_), toString_lBEoN6A9bKNublZsSxuhYeA(T26_));
				nimln_(502, "strutils.nim");
				(*colonenvP_).last7 = ((NI) 0);
				nimln_(503, "strutils.nim");
				(*colonenvP_).splits8 = ((NI) -1);
				{
					nimln_(641, "strutils.nim");
					while (1) {
						NI TM_4wr9busLgulMeCFBdHSvIuw_24;
						NI TM_4wr9busLgulMeCFBdHSvIuw_26;
						NI TM_4wr9busLgulMeCFBdHSvIuw_27;
						nimln_(505, "strutils.nim");
						nimln_(641, "strutils.nim");
						if (!((*colonenvP_).last7 <= ((*colonenvP_).colontmp6_ ? (*colonenvP_).colontmp6_->Sup.len : 0))) goto LA28;
						nimln_(506, "strutils.nim");
						(*colonenvP_).first9 = (*colonenvP_).last7;
						{
							nimln_(507, "strutils.nim");
							while (1) {
								NIM_BOOL T31_;
								NI TM_4wr9busLgulMeCFBdHSvIuw_23;
								T31_ = (NIM_BOOL)0;
								nimln_(641, "strutils.nim");
								T31_ = ((*colonenvP_).last7 < ((*colonenvP_).colontmp6_ ? (*colonenvP_).colontmp6_->Sup.len : 0));
								if (!(T31_)) goto LA32_;
								nimln_(507, "strutils.nim");
								nimln_(495, "strutils.nim");
								if ((NU)((*colonenvP_).last7) > (NU)((*colonenvP_).colontmp6_->Sup.len)) raiseIndexError();
								T31_ = !(((NU8)((*colonenvP_).colontmp6_->data[(*colonenvP_).last7]) == (NU8)(44)));
								LA32_: ;
								if (!T31_) goto LA30;
								nimln_(508, "strutils.nim");
								TM_4wr9busLgulMeCFBdHSvIuw_23 = addInt((*colonenvP_).last7, ((NI) 1));
								(*colonenvP_).last7 = (NI)(TM_4wr9busLgulMeCFBdHSvIuw_23);
							} LA30: ;
						}
						nimln_(509, "strutils.nim");
						{
							if (!((*colonenvP_).splits8 == ((NI) 0))) goto LA35_;
							nimln_(641, "strutils.nim");
							(*colonenvP_).last7 = ((*colonenvP_).colontmp6_ ? (*colonenvP_).colontmp6_->Sup.len : 0);
						}
						LA35_: ;
						nimln_(510, "strutils.nim");
						TM_4wr9busLgulMeCFBdHSvIuw_24 = subInt((*colonenvP_).last7, ((NI) 1));
						asgnRefNoCycle((void**) (&(*colonenvP_).it5), copyStrLast((*colonenvP_).colontmp6_, (*colonenvP_).first9, (NI)(TM_4wr9busLgulMeCFBdHSvIuw_24)));
						nimln_(101, "server.nim");
						{
							NimStringDesc* T39_;
							NimStringDesc* T40_;
							T39_ = (NimStringDesc*)0;
							T39_ = nsuStrip((*colonenvP_).it5, NIM_TRUE, NIM_TRUE, TM_4wr9busLgulMeCFBdHSvIuw_25);
							T40_ = (NimStringDesc*)0;
							T40_ = nsuToLowerAsciiStr(T39_);
							if (!eqStrings((*colonenvP_).prot4, T40_)) goto LA41_;
							nimln_(102, "server.nim");
							goto LA24;
						}
						LA41_: ;
						nimln_(511, "strutils.nim");
						{
							if (!((*colonenvP_).splits8 == ((NI) 0))) goto LA45_;
							goto LA27;
						}
						LA45_: ;
						nimln_(512, "strutils.nim");
						TM_4wr9busLgulMeCFBdHSvIuw_26 = subInt((*colonenvP_).splits8, ((NI) 1));
						(*colonenvP_).splits8 = (NI)(TM_4wr9busLgulMeCFBdHSvIuw_26);
						nimln_(513, "strutils.nim");
						TM_4wr9busLgulMeCFBdHSvIuw_27 = addInt((*colonenvP_).last7, ((NI) 1));
						(*colonenvP_).last7 = (NI)(TM_4wr9busLgulMeCFBdHSvIuw_27);
					} LA28: ;
				} LA27: ;
			}
			nimln_(104, "server.nim");
			T47_ = (NimStringDesc*)0;
			T47_ = rawNewString((*(*colonenvP_).colonup_).protocol3->Sup.len + 50);
appendString(T47_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_28));
appendString(T47_, (*(*colonenvP_).colonup_).protocol3);
appendString(T47_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_29));
			asgnRefNoCycle((void**) (&(*colonenvP_).result1.Field1), T47_);
			nimln_(343, "asyncmacro.nim");
			complete_9cdCqj3ph8OkumBYITLkE2Q((*(*colonenvP_).colonup_).retFuture2, (*colonenvP_).result1);
			(*colonenvP_).colonstate_ = ((NI) -1);
			nimln_(80, "server.nim");
			nimln_(1157, "os.nim");
			result = NIM_NIL;
			goto BeforeRet_;
		} LA24: ;
	}
	goto LA14_;
	LA17_: ;
	{
		NimStringDesc* T51_;
		nimln_(105, "server.nim");
		if (!!((*colonenvP_).noProtocol3)) goto LA49_;
		nimln_(106, "server.nim");
		T51_ = (NimStringDesc*)0;
		T51_ = rawNewString((*(*colonenvP_).colonup_).protocol3->Sup.len + 45);
appendString(T51_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_30));
appendString(T51_, (*(*colonenvP_).colonup_).protocol3);
appendString(T51_, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_29));
		asgnRefNoCycle((void**) (&(*colonenvP_).result1.Field1), T51_);
		nimln_(343, "asyncmacro.nim");
		complete_9cdCqj3ph8OkumBYITLkE2Q((*(*colonenvP_).colonup_).retFuture2, (*colonenvP_).result1);
		(*colonenvP_).colonstate_ = ((NI) -1);
		nimln_(80, "server.nim");
		nimln_(1157, "os.nim");
		result = NIM_NIL;
		goto BeforeRet_;
	}
	goto LA14_;
	LA49_: ;
	LA14_: ;
	nimln_(108, "server.nim");
	T52_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
	T52_ = X5BX5D__2I7W00Lgs3jqrdJTli4b9cA((*(*colonenvP_).colonup_).req1.headers, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_19));
	T53_ = (NimStringDesc*)0;
	T53_ = toString_lBEoN6A9bKNublZsSxuhYeA(T52_);
	asgnRefNoCycle((void**) (&(*colonenvP_).msg10), makeHandshakeResponse_eRqpPEOg3sGrMOFQbu5WbQ(T53_, (*(*colonenvP_).colonup_).protocol3));
	nimln_(109, "server.nim");
	asgnRef((void**) (&(*colonenvP_).future11), send_AqMRJAH66soP1Q6GLXU5LA((*(*colonenvP_).colonup_).req1.client, (*colonenvP_).msg10, 2));
	(*colonenvP_).colonstate_ = ((NI) 1);
	nimln_(132, "asyncmacro.nim");
	result = &(*colonenvP_).future11->Sup;
	goto BeforeRet_;
	STATE1: ;
	read_EYgDXwwneJeAEUfXLUHmhg((*colonenvP_).future11);
	nimln_(111, "server.nim");
	if ((*colonenvP_).result1.Field0) { nimGCunrefRC1((*colonenvP_).result1.Field0); (*colonenvP_).result1.Field0 = NIM_NIL; }
	(*colonenvP_).result1.Field0 = (tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw*) newObjRC1((&NTI_inAXQwjH33JjtLPhTcLm9cg_), sizeof(tyObject_AsyncWebSocketObj_FO7G9bZCP6FlKF64Vby7eGw));
	(*(*colonenvP_).result1.Field0).Sup.m_type = (&NTI_FO7G9bZCP6FlKF64Vby7eGw_);
	nimln_(112, "server.nim");
	(*(*colonenvP_).result1.Field0).kind = ((tyEnum_SocketKind_LVqgZYstYjAJSuADJ9bp5XA) 1);
	nimln_(113, "server.nim");
	asgnRef((void**) (&(*(*colonenvP_).result1.Field0).sock), (*(*colonenvP_).colonup_).req1.client);
	nimln_(114, "server.nim");
	T54_ = (NimStringDesc*)0;
	T54_ = (*(*colonenvP_).result1.Field0).protocol; (*(*colonenvP_).result1.Field0).protocol = copyStringRC1((*(*colonenvP_).colonup_).protocol3);
	if (T54_) nimGCunrefNoCycle(T54_);
	nimln_(116, "server.nim");
	T55_ = (NimStringDesc*)0;
	T55_ = (*colonenvP_).result1.Field1; (*colonenvP_).result1.Field1 = copyStringRC1(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_15));
	if (T55_) nimGCunrefNoCycle(T55_);
	nimln_(343, "asyncmacro.nim");
	complete_9cdCqj3ph8OkumBYITLkE2Q((*(*colonenvP_).colonup_).retFuture2, (*colonenvP_).result1);
	(*colonenvP_).colonstate_ = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

static N_INLINE(NIM_BOOL, finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch)(tyProc_3cmVDZYspcmD9a16VGUFJoA x) {
	NIM_BOOL result;
	nimfr_("finished", "system.nim");
	result = (NIM_BOOL)0;
	nimln_(3399, "system.nim");
	      result = ((NI*) x.ClE_0)[1] < 0;
      
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr_("getCurrentException", "system.nim");
	result = (Exception*)0;
	nimln_(3350, "system.nim");
	result = currException_9bVPeDJlYTi9bQApZpfH8wjg;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException_9bVPeDJlYTi9bQApZpfH8wjg), (*currException_9bVPeDJlYTi9bQApZpfH8wjg).up);
}

N_LIB_PRIVATE N_CLOSURE(void, verifyWebsocketRequest_continue_giCns6lOo9c9c8HtPb8uh1uw)(void* ClE_0) {
	tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw* colonenvP_;
	TSafePoint TM_4wr9busLgulMeCFBdHSvIuw_31;
	nimfr_("verifyWebsocketRequest_continue", "asyncmacro.nim");
	colonenvP_ = (tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw*) ClE_0;
	nimln_(32, "asyncmacro.nim");
	pushSafePoint(&TM_4wr9busLgulMeCFBdHSvIuw_31);
	TM_4wr9busLgulMeCFBdHSvIuw_31.status = setjmp(TM_4wr9busLgulMeCFBdHSvIuw_31.context);
	if (TM_4wr9busLgulMeCFBdHSvIuw_31.status == 0) {
		nimln_(33, "asyncmacro.nim");
		{
			NIM_BOOL T4_;
			tyObject_FutureBasecolonObjectType__cnXnCCtV9cjKaEq9alHheOFg* volatile next;
			T4_ = (NIM_BOOL)0;
			T4_ = finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch((*colonenvP_).nameIterVar4);
			if (!!(T4_)) goto LA5_;
			nimln_(34, "asyncmacro.nim");
			next = (*colonenvP_).nameIterVar4.ClP_0((*colonenvP_).nameIterVar4.ClE_0);
			{
				nimln_(36, "asyncmacro.nim");
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = !((next == 0));
					if (!(T9_)) goto LA10_;
					T9_ = finished_ZDnEFECD9b9aKFsuVLxFyzkA_2(next);
					LA10_: ;
					if (!T9_) goto LA8;
					nimln_(37, "asyncmacro.nim");
					next = (*colonenvP_).nameIterVar4.ClP_0((*colonenvP_).nameIterVar4.ClE_0);
					nimln_(38, "asyncmacro.nim");
					{
						NIM_BOOL T13_;
						T13_ = (NIM_BOOL)0;
						T13_ = finished_lnX3UZC8cmCUb7BzjNqokQasyncdispatch((*colonenvP_).nameIterVar4);
						if (!T13_) goto LA14_;
						nimln_(39, "asyncmacro.nim");
						goto LA7;
					}
					LA14_: ;
				} LA8: ;
			} LA7: ;
			nimln_(41, "asyncmacro.nim");
			{
				if (!(next == NIM_NIL)) goto LA18_;
				nimln_(42, "asyncmacro.nim");
				{
					NIM_BOOL T22_;
					NimStringDesc* msg;
					tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA* volatile e;
					nimln_(401, "asyncmacro.nim");
					T22_ = (NIM_BOOL)0;
					T22_ = finished_ntBlpNGvne9cEZGeELSM9cOg((*colonenvP_).retFuture2);
					if (!!(T22_)) goto LA23_;
					nimln_(43, "asyncmacro.nim");
					msg = copyString(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_34));
					e = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*)0;
					nimln_(2811, "system.nim");
					e = (tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA*) newObj((&NTI_TmgWlPUbRr7iGD2UE1cu6A_), sizeof(tyObject_AssertionError_8FC9arcap3s5ZtfMs75krtA));
					(*e).Sup.Sup.m_type = (&NTI_8FC9arcap3s5ZtfMs75krtA_);
					nimln_(45, "asyncmacro.nim");
					asgnRefNoCycle((void**) (&(*e).Sup.message), nsuFormatSingleElem(msg, ((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_11)));
					nimln_(2806, "system.nim");
					asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
					nimln_(45, "asyncmacro.nim");
					raiseException((Exception*)e, "AssertionError");
				}
				LA23_: ;
			}
			goto LA16_;
			LA18_: ;
			{
				tyProc_IIomJ6ptE6vfJ5zRbATgkQ T26_;
				nimln_(49, "asyncmacro.nim");
				memset((void*)(&T26_), 0, sizeof(T26_));
				T26_.ClP_0 = verifyWebsocketRequest_continue_giCns6lOo9c9c8HtPb8uh1uw; T26_.ClE_0 = colonenvP_;
				callbackeq__9c5z7ouO5bUylgKxaZoIuVg_2(next, T26_);
			}
			LA16_: ;
		}
		LA5_: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR_);
		{
			TM_4wr9busLgulMeCFBdHSvIuw_31.status = 0;
			nimln_(54, "asyncmacro.nim");
			{
				NIM_BOOL T31_;
				nimln_(401, "asyncmacro.nim");
				T31_ = (NIM_BOOL)0;
				T31_ = finished_ntBlpNGvne9cEZGeELSM9cOg((*colonenvP_).retFuture2);
				if (!T31_) goto LA32_;
				nimln_(57, "asyncmacro.nim");
				reraiseException();
			}
			goto LA29_;
			LA32_: ;
			{
				Exception* T35_;
				nimln_(401, "asyncmacro.nim");
				nimln_(59, "asyncmacro.nim");
				T35_ = (Exception*)0;
				T35_ = getCurrentException();
				fail_DC8NBOnruQLZx4YiAhYmtw((*colonenvP_).retFuture2, T35_);
			}
			LA29_: ;
			popCurrentException();
		}
	}
	if (TM_4wr9busLgulMeCFBdHSvIuw_31.status != 0) reraiseException();
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg*, verifyWebsocketRequest_fcA3f463uAvV9bTbiyyDV8w)(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ* req, NimStringDesc* protocol) {
	tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg* result;
	tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw* colonenv_;
	NimStringDesc* T1_;
	tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ* colonenv__2;
	tyProc_3cmVDZYspcmD9a16VGUFJoA T2_;
	tyProc_IIomJ6ptE6vfJ5zRbATgkQ T3_;
	nimfr_("verifyWebsocketRequest", "server.nim");
{	result = (tyObject_FuturecolonObjectType__3hfLWf9axLEezHvpizjqnpg*)0;
	colonenv_ = (tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw*)0;
	nimln_(58, "server.nim");
	colonenv_ = (tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw*) newObj((&NTI_jyDW3skhKMaCr8hmgg44Pg_), sizeof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw));
	(*colonenv_).Sup.m_type = (&NTI_BLtPjr3JJTiIlIuaqlnxbw_);
	genericAssign((void*)(&(*colonenv_).req1), (void*)req, (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_));
	T1_ = (NimStringDesc*)0;
	T1_ = (*colonenv_).protocol3; (*colonenv_).protocol3 = copyStringRC1(protocol);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*colonenv_).retFuture2), newFuture_tn8LGE0sZTkiYNWWIOkQAQ(((NimStringDesc*) &TM_4wr9busLgulMeCFBdHSvIuw_11)));
	nimln_(29, "asyncmacro.nim");
	colonenv__2 = (tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ*)0;
	nimln_(401, "asyncmacro.nim");
	colonenv__2 = (tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ*) newObj((&NTI_vFUUP2xqC6NqYC9cxtYPsoQ_), sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ));
	(*colonenv__2).Sup.m_type = (&NTI_f7vzrmTkU1fEyae7tCDJHQ_);
	nimln_(58, "server.nim");
	asgnRef((void**) (&(*colonenv__2).colonup_), colonenv_);
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = verifyWebsocketRequestIter_tzF9cEK9bDvzwAcUnBk9bNAXQ; T2_.ClE_0 = colonenv__2;
	asgnRef((void**) (&(*colonenv_).nameIterVar4.ClE_0), T2_.ClE_0);
	(*colonenv_).nameIterVar4.ClP_0 = T2_.ClP_0;
	nimln_(401, "asyncmacro.nim");
	memset((void*)(&T3_), 0, sizeof(T3_));
	T3_.ClP_0 = verifyWebsocketRequest_continue_giCns6lOo9c9c8HtPb8uh1uw; T3_.ClE_0 = colonenv_;
	T3_.ClE_0? T3_.ClP_0(T3_.ClE_0):((TM_4wr9busLgulMeCFBdHSvIuw_35)(T3_.ClP_0))();
	nimln_(58, "server.nim");
	nimln_(401, "asyncmacro.nim");
	result = (*colonenv_).retFuture2;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, websocket_serverInit000)(void) {
	nimfr_("server", "server.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, websocket_serverDatInit000)(void) {
static TNimNode* TM_4wr9busLgulMeCFBdHSvIuw_9[5];
static TNimNode* TM_4wr9busLgulMeCFBdHSvIuw_10[2];
static TNimNode* TM_4wr9busLgulMeCFBdHSvIuw_12[12];
static TNimNode TM_4wr9busLgulMeCFBdHSvIuw_0[22];
NTI_BLtPjr3JJTiIlIuaqlnxbw_.size = sizeof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw);
NTI_BLtPjr3JJTiIlIuaqlnxbw_.kind = 17;
NTI_BLtPjr3JJTiIlIuaqlnxbw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_4wr9busLgulMeCFBdHSvIuw_9[0] = &TM_4wr9busLgulMeCFBdHSvIuw_0[1];
TM_4wr9busLgulMeCFBdHSvIuw_0[1].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[1].offset = offsetof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw, colonstate_);
TM_4wr9busLgulMeCFBdHSvIuw_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_4wr9busLgulMeCFBdHSvIuw_0[1].name = ":state";
TM_4wr9busLgulMeCFBdHSvIuw_9[1] = &TM_4wr9busLgulMeCFBdHSvIuw_0[2];
TM_4wr9busLgulMeCFBdHSvIuw_0[2].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[2].offset = offsetof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw, req1);
TM_4wr9busLgulMeCFBdHSvIuw_0[2].typ = (&NTI_1Wfxxtqzahm0R6lueM9aQmQ_);
TM_4wr9busLgulMeCFBdHSvIuw_0[2].name = "req1";
TM_4wr9busLgulMeCFBdHSvIuw_9[2] = &TM_4wr9busLgulMeCFBdHSvIuw_0[3];
NTI_S3HkVX1vbi9cJcN9b3B7gRkw_.size = sizeof(tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw);
NTI_S3HkVX1vbi9cJcN9b3B7gRkw_.kind = 18;
NTI_S3HkVX1vbi9cJcN9b3B7gRkw_.base = 0;
TM_4wr9busLgulMeCFBdHSvIuw_10[0] = &TM_4wr9busLgulMeCFBdHSvIuw_0[5];
TM_4wr9busLgulMeCFBdHSvIuw_0[5].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[5].offset = offsetof(tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw, Field0);
TM_4wr9busLgulMeCFBdHSvIuw_0[5].typ = (&NTI_inAXQwjH33JjtLPhTcLm9cg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[5].name = "Field0";
TM_4wr9busLgulMeCFBdHSvIuw_10[1] = &TM_4wr9busLgulMeCFBdHSvIuw_0[6];
TM_4wr9busLgulMeCFBdHSvIuw_0[6].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[6].offset = offsetof(tyTuple_S3HkVX1vbi9cJcN9b3B7gRkw, Field1);
TM_4wr9busLgulMeCFBdHSvIuw_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[6].name = "Field1";
TM_4wr9busLgulMeCFBdHSvIuw_0[4].len = 2; TM_4wr9busLgulMeCFBdHSvIuw_0[4].kind = 2; TM_4wr9busLgulMeCFBdHSvIuw_0[4].sons = &TM_4wr9busLgulMeCFBdHSvIuw_10[0];
NTI_S3HkVX1vbi9cJcN9b3B7gRkw_.node = &TM_4wr9busLgulMeCFBdHSvIuw_0[4];
TM_4wr9busLgulMeCFBdHSvIuw_0[3].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[3].offset = offsetof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw, retFuture2);
TM_4wr9busLgulMeCFBdHSvIuw_0[3].typ = (&NTI_kTAkTyBCGf7Dtp1iey59asg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[3].name = "retFuture2";
TM_4wr9busLgulMeCFBdHSvIuw_9[3] = &TM_4wr9busLgulMeCFBdHSvIuw_0[7];
TM_4wr9busLgulMeCFBdHSvIuw_0[7].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[7].offset = offsetof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw, protocol3);
TM_4wr9busLgulMeCFBdHSvIuw_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[7].name = "protocol3";
TM_4wr9busLgulMeCFBdHSvIuw_9[4] = &TM_4wr9busLgulMeCFBdHSvIuw_0[8];
TM_4wr9busLgulMeCFBdHSvIuw_0[8].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[8].offset = offsetof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw, nameIterVar4);
TM_4wr9busLgulMeCFBdHSvIuw_0[8].typ = (&NTI_3cmVDZYspcmD9a16VGUFJoA_);
TM_4wr9busLgulMeCFBdHSvIuw_0[8].name = "nameIterVar4";
TM_4wr9busLgulMeCFBdHSvIuw_0[0].len = 5; TM_4wr9busLgulMeCFBdHSvIuw_0[0].kind = 2; TM_4wr9busLgulMeCFBdHSvIuw_0[0].sons = &TM_4wr9busLgulMeCFBdHSvIuw_9[0];
NTI_BLtPjr3JJTiIlIuaqlnxbw_.node = &TM_4wr9busLgulMeCFBdHSvIuw_0[0];
NTI_jyDW3skhKMaCr8hmgg44Pg_.size = sizeof(tyObject_Env_slashhomeslashryanslashdotnimbleslashpkgsslashwebsocketminusX23headslashwebsocketslashserverdotnim__BLtPjr3JJTiIlIuaqlnxbw*);
NTI_jyDW3skhKMaCr8hmgg44Pg_.kind = 22;
NTI_jyDW3skhKMaCr8hmgg44Pg_.base = (&NTI_BLtPjr3JJTiIlIuaqlnxbw_);
NTI_jyDW3skhKMaCr8hmgg44Pg_.marker = Marker_tyRef_jyDW3skhKMaCr8hmgg44Pg;
NTI_f7vzrmTkU1fEyae7tCDJHQ_.size = sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ);
NTI_f7vzrmTkU1fEyae7tCDJHQ_.kind = 17;
NTI_f7vzrmTkU1fEyae7tCDJHQ_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_4wr9busLgulMeCFBdHSvIuw_12[0] = &TM_4wr9busLgulMeCFBdHSvIuw_0[10];
TM_4wr9busLgulMeCFBdHSvIuw_0[10].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[10].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, colonstate_);
TM_4wr9busLgulMeCFBdHSvIuw_0[10].typ = (&NTI_Mpt8aZ13tT2AYV71yyfHcA_);
TM_4wr9busLgulMeCFBdHSvIuw_0[10].name = ":state";
TM_4wr9busLgulMeCFBdHSvIuw_12[1] = &TM_4wr9busLgulMeCFBdHSvIuw_0[11];
TM_4wr9busLgulMeCFBdHSvIuw_0[11].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[11].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, result1);
TM_4wr9busLgulMeCFBdHSvIuw_0[11].typ = (&NTI_S3HkVX1vbi9cJcN9b3B7gRkw_);
TM_4wr9busLgulMeCFBdHSvIuw_0[11].name = "result1";
TM_4wr9busLgulMeCFBdHSvIuw_12[2] = &TM_4wr9busLgulMeCFBdHSvIuw_0[12];
TM_4wr9busLgulMeCFBdHSvIuw_0[12].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[12].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, colonup_);
TM_4wr9busLgulMeCFBdHSvIuw_0[12].typ = (&NTI_jyDW3skhKMaCr8hmgg44Pg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[12].name = ":up";
TM_4wr9busLgulMeCFBdHSvIuw_12[3] = &TM_4wr9busLgulMeCFBdHSvIuw_0[13];
TM_4wr9busLgulMeCFBdHSvIuw_0[13].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[13].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, noProtocol3);
TM_4wr9busLgulMeCFBdHSvIuw_0[13].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_4wr9busLgulMeCFBdHSvIuw_0[13].name = "noProtocol3";
TM_4wr9busLgulMeCFBdHSvIuw_12[4] = &TM_4wr9busLgulMeCFBdHSvIuw_0[14];
TM_4wr9busLgulMeCFBdHSvIuw_0[14].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[14].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, prot4);
TM_4wr9busLgulMeCFBdHSvIuw_0[14].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[14].name = "prot4";
TM_4wr9busLgulMeCFBdHSvIuw_12[5] = &TM_4wr9busLgulMeCFBdHSvIuw_0[15];
TM_4wr9busLgulMeCFBdHSvIuw_0[15].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[15].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, it5);
TM_4wr9busLgulMeCFBdHSvIuw_0[15].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[15].name = "it5";
TM_4wr9busLgulMeCFBdHSvIuw_12[6] = &TM_4wr9busLgulMeCFBdHSvIuw_0[16];
TM_4wr9busLgulMeCFBdHSvIuw_0[16].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[16].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, colontmp6_);
TM_4wr9busLgulMeCFBdHSvIuw_0[16].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[16].name = ":tmp6";
TM_4wr9busLgulMeCFBdHSvIuw_12[7] = &TM_4wr9busLgulMeCFBdHSvIuw_0[17];
TM_4wr9busLgulMeCFBdHSvIuw_0[17].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[17].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, last7);
TM_4wr9busLgulMeCFBdHSvIuw_0[17].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4wr9busLgulMeCFBdHSvIuw_0[17].name = "last7";
TM_4wr9busLgulMeCFBdHSvIuw_12[8] = &TM_4wr9busLgulMeCFBdHSvIuw_0[18];
TM_4wr9busLgulMeCFBdHSvIuw_0[18].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[18].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, splits8);
TM_4wr9busLgulMeCFBdHSvIuw_0[18].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4wr9busLgulMeCFBdHSvIuw_0[18].name = "splits8";
TM_4wr9busLgulMeCFBdHSvIuw_12[9] = &TM_4wr9busLgulMeCFBdHSvIuw_0[19];
TM_4wr9busLgulMeCFBdHSvIuw_0[19].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[19].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, first9);
TM_4wr9busLgulMeCFBdHSvIuw_0[19].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4wr9busLgulMeCFBdHSvIuw_0[19].name = "first9";
TM_4wr9busLgulMeCFBdHSvIuw_12[10] = &TM_4wr9busLgulMeCFBdHSvIuw_0[20];
TM_4wr9busLgulMeCFBdHSvIuw_0[20].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[20].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, msg10);
TM_4wr9busLgulMeCFBdHSvIuw_0[20].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[20].name = "msg10";
TM_4wr9busLgulMeCFBdHSvIuw_12[11] = &TM_4wr9busLgulMeCFBdHSvIuw_0[21];
TM_4wr9busLgulMeCFBdHSvIuw_0[21].kind = 1;
TM_4wr9busLgulMeCFBdHSvIuw_0[21].offset = offsetof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ, future11);
TM_4wr9busLgulMeCFBdHSvIuw_0[21].typ = (&NTI_zXD0JrbeCNyAaW4E6fB9aqg_);
TM_4wr9busLgulMeCFBdHSvIuw_0[21].name = "future11";
TM_4wr9busLgulMeCFBdHSvIuw_0[9].len = 12; TM_4wr9busLgulMeCFBdHSvIuw_0[9].kind = 2; TM_4wr9busLgulMeCFBdHSvIuw_0[9].sons = &TM_4wr9busLgulMeCFBdHSvIuw_12[0];
NTI_f7vzrmTkU1fEyae7tCDJHQ_.node = &TM_4wr9busLgulMeCFBdHSvIuw_0[9];
NTI_vFUUP2xqC6NqYC9cxtYPsoQ_.size = sizeof(tyObject_Env_libslashpureslashasyncmacrodotnim__f7vzrmTkU1fEyae7tCDJHQ*);
NTI_vFUUP2xqC6NqYC9cxtYPsoQ_.kind = 22;
NTI_vFUUP2xqC6NqYC9cxtYPsoQ_.base = (&NTI_f7vzrmTkU1fEyae7tCDJHQ_);
NTI_vFUUP2xqC6NqYC9cxtYPsoQ_.marker = Marker_tyRef_vFUUP2xqC6NqYC9cxtYPsoQ;
}

