/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/ryan/.choosenim/toolchains/nim-0.18.0/lib -o /home/ryan/dev/slackbot/src/nimcache/websocket_hex.o /home/ryan/dev/slackbot/src/nimcache/websocket_hex.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
N_LIB_PRIVATE N_NIMCALL(NI, nibbleFromChar_6Lp9cf1Y3JYfnXhmIpZmyNQ)(NIM_CHAR c);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeHex_lfVYv8z1eInCBADVgGvZWw)(NimStringDesc* str);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NIM_CHAR, nibbleToChar_pasoBlUR2gN2wp31Nz19b4whex)(NI nibble);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeHex_lfVYv8z1eInCBADVgGvZWw_2)(NimStringDesc* str);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray_Wfh9bjgBQ4UqJsyISUuDSuA byteMap_IKv9b2kEFbRICsYsOtKszNA = {48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
97,
98,
99,
100,
101,
102}
;

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NI, nibbleFromChar_6Lp9cf1Y3JYfnXhmIpZmyNQ)(NIM_CHAR c) {
	NI result;
	nimfr_("nibbleFromChar", "hex.nim");
	result = (NI)0;
	nimln_(2, "hex.nim");
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_2;
		nimln_(3, "hex.nim");
		TM_P9bFTUR9atvQ67Z6e8gUqBIQ_2 = subInt(((NU8)(c)), ((NI) 48));
		result = (NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_2);
	}
	break;
	case 97 ... 102:
	{
		NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_3;
		NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_4;
		nimln_(4, "hex.nim");
		TM_P9bFTUR9atvQ67Z6e8gUqBIQ_3 = subInt(((NU8)(c)), ((NI) 97));
		TM_P9bFTUR9atvQ67Z6e8gUqBIQ_4 = addInt((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_3), ((NI) 10));
		result = (NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_4);
	}
	break;
	case 65 ... 70:
	{
		NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_5;
		NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_6;
		nimln_(5, "hex.nim");
		TM_P9bFTUR9atvQ67Z6e8gUqBIQ_5 = subInt(((NU8)(c)), ((NI) 65));
		TM_P9bFTUR9atvQ67Z6e8gUqBIQ_6 = addInt((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_5), ((NI) 10));
		result = (NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_6);
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeHex_lfVYv8z1eInCBADVgGvZWw)(NimStringDesc* str) {
	NimStringDesc* result;
	NI length;
	NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_7;
	nimfr_("decodeHex", "hex.nim");
	result = (NimStringDesc*)0;
	nimln_(9, "hex.nim");
	TM_P9bFTUR9atvQ67Z6e8gUqBIQ_7 = divInt((str ? str->Sup.len : 0), ((NI) 2));
	length = (NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_7);
	nimln_(10, "hex.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_8;
				NI T4_;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_9;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_10;
				NI T5_;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_11;
				if (!(i_2 < length)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(12, "hex.nim");
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_8 = mulInt(((NI) 2), i);
				if ((NU)((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_8)) > (NU)(str->Sup.len)) raiseIndexError();
				T4_ = (NI)0;
				T4_ = nibbleFromChar_6Lp9cf1Y3JYfnXhmIpZmyNQ(str->data[(NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_8)]);
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_9 = mulInt(((NI) 2), i);
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_10 = addInt((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_9), ((NI) 1));
				if ((NU)((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_10)) > (NU)(str->Sup.len)) raiseIndexError();
				T5_ = (NI)0;
				T5_ = nibbleFromChar_6Lp9cf1Y3JYfnXhmIpZmyNQ(str->data[(NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_10)]);
				result->data[i] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(T4_) << (NU64)(((NI) 4))) | T5_), ((NI) 0), ((NI) 255)))));
				nimln_(3522, "system.nim");
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_11 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_11);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NIM_CHAR, nibbleToChar_pasoBlUR2gN2wp31Nz19b4whex)(NI nibble) {
	NIM_CHAR result;
	nimfr_("nibbleToChar", "hex.nim");
{	result = (NIM_CHAR)0;
	nimln_(16, "hex.nim");
	if ((NU)(nibble) > (NU)(15)) raiseIndexError();
	result = byteMap_IKv9b2kEFbRICsYsOtKszNA[(nibble)- 0];
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeHex_lfVYv8z1eInCBADVgGvZWw_2)(NimStringDesc* str) {
	NimStringDesc* result;
	NI length;
	NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_12;
	nimfr_("encodeHex", "hex.nim");
	result = (NimStringDesc*)0;
	nimln_(19, "hex.nim");
	length = (str ? str->Sup.len : 0);
	nimln_(20, "hex.nim");
	TM_P9bFTUR9atvQ67Z6e8gUqBIQ_12 = mulInt(length, ((NI) 2));
	result = mnewString(((NI)chckRange((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_12), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI a;
				NI b;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_13;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_14;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_15;
				NI TM_P9bFTUR9atvQ67Z6e8gUqBIQ_16;
				if (!(i_2 < length)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				nimln_(22, "hex.nim");
				if ((NU)(i) > (NU)(str->Sup.len)) raiseIndexError();
				a = (NI)((NI)((NU64)(((NU8)(str->data[i]))) >> (NU64)(((NI) 4))) & ((NI) 15));
				nimln_(23, "hex.nim");
				if ((NU)(i) > (NU)(str->Sup.len)) raiseIndexError();
				b = (NI)(((NU8)(str->data[i])) & ((NI) 15));
				nimln_(24, "hex.nim");
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_13 = mulInt(i, ((NI) 2));
				if ((NU)((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_13)) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[(NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_13)] = nibbleToChar_pasoBlUR2gN2wp31Nz19b4whex(a);
				nimln_(25, "hex.nim");
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_14 = mulInt(i, ((NI) 2));
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_15 = addInt((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_14), ((NI) 1));
				if ((NU)((NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_15)) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[(NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_15)] = nibbleToChar_pasoBlUR2gN2wp31Nz19b4whex(b);
				nimln_(3522, "system.nim");
				TM_P9bFTUR9atvQ67Z6e8gUqBIQ_16 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_P9bFTUR9atvQ67Z6e8gUqBIQ_16);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, websocket_hexInit000)(void) {
	nimfr_("hex", "hex.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, websocket_hexDatInit000)(void) {
}

